import type { ProductId } from "@hypermyths/theme";

export const HASHMYTH_VIDEO_SOURCES = [
  "token", "wallet", "x_profile", "market_thesis",
  "research_report", "simulation", "ad_campaign",
  "script", "prompt", "document", "terminal_chat",
  "feed_item", "belief_timeline"
] as const;

export type HashMythVideoSource = typeof HASHMYTH_VIDEO_SOURCES[number];

export type HashMythVideoJobStatus =
  | "prepared"
  | "quoted"
  | "requires_payment"
  | "queued"
  | "running"
  | "complete"
  | "failed"
  | "cancelled";

export type VideoScript = {
  title: string;
  narration: string;
  captions: string[];
  scenes: VideoScene[];
  visualPrompts: string[];
  durationEstimateSeconds: number;
};

export type VideoScene = {
  index: number;
  description: string;
  visualPrompt: string;
  narration: string;
  durationSeconds: number;
  shotType: "wide" | "medium" | "close_up" | "aerial" | "abstract";
};

export type HashMythVideoJob = {
  id: string;
  source: HashMythVideoSource;
  status: HashMythVideoJobStatus;
  script: VideoScript;
  productId?: ProductId;
  inputPayload?: Record<string, unknown>;
  quote?: HashMythVideoQuote;
  paymentReceiptId?: string;
  outputUrl?: string;
  artifactId?: string;
  feedItemId?: string;
  error?: string;
  createdAt: string;
  updatedAt: string;
};

export type HashMythVideoQuote = {
  id: string;
  estimatedCostUsd: number;
  currency: string;
  provider: "pay.sh" | "free" | "internal_credit";
  expiresAt: string;
  createdAt: string;
};

export type HashMythVideoCapabilities = {
  supportedSources: string[];
  supportedOutputs: string[];
  maxDurationSeconds: number;
  maxScenes: number;
  rendererConfigured: boolean;
  payShConfigured: boolean;
  acceptsArbitraryPrompt: boolean;
  supportsDocumentUpload: boolean;
};

export function buildVideoScript(input: {
  title: string;
  sourcePrompt: string;
  source: HashMythVideoSource;
}): VideoScript {
  const title = input.title || `Video from ${input.source}`;
  const narration = input.sourcePrompt
    ? `Narration generated from ${input.source} input: ${input.sourcePrompt.slice(0, 200)}`
    : `Automated video narration for ${title}`;
  const scenes: VideoScene[] = [
    {
      index: 0,
      description: `Opening scene for ${title}`,
      visualPrompt: `${input.source} video opening, cinematic style`,
      narration: narration.slice(0, 100),
      durationSeconds: 5,
      shotType: "wide"
    },
    {
      index: 1,
      description: `Core content from ${input.source}`,
      visualPrompt: `abstract visualization of ${input.source.replace(/_/g, " ")}`,
      narration: narration.slice(0, 150),
      durationSeconds: 8,
      shotType: "medium"
    },
    {
      index: 2,
      description: `Closing scene`,
      visualPrompt: `HashMyth video outro, purple gradient`,
      narration: `Generated by HashMyth Video Engine`,
      durationSeconds: 3,
      shotType: "abstract"
    }
  ];

  return {
    title,
    narration,
    captions: [narration.slice(0, 80)],
    scenes,
    visualPrompts: scenes.map((s) => s.visualPrompt),
    durationEstimateSeconds: scenes.reduce((sum, s) => sum + s.durationSeconds, 0)
  };
}

export function prepareHashMythVideo(input: {
  productId?: ProductId;
  title: string;
  sourcePrompt: string;
  source: HashMythVideoSource;
  inputPayload?: Record<string, unknown>;
}): HashMythVideoJob {
  const now = new Date().toISOString();
  return {
    id: crypto.randomUUID(),
    source: input.source,
    status: "prepared",
    script: buildVideoScript(input),
    productId: input.productId,
    inputPayload: input.inputPayload,
    createdAt: now,
    updatedAt: now
  };
}

export function quoteHashMythVideo(job: HashMythVideoJob): HashMythVideoJob {
  const quote: HashMythVideoQuote = {
    id: crypto.randomUUID(),
    estimatedCostUsd: 0,
    currency: "USDC",
    provider: "free",
    expiresAt: new Date(Date.now() + 3600000).toISOString(),
    createdAt: new Date().toISOString()
  };
  return { ...job, status: "quoted", quote, updatedAt: new Date().toISOString() };
}

export function cancelHashMythVideo(job: HashMythVideoJob): HashMythVideoJob {
  if (job.status === "complete" || job.status === "failed") {
    return { ...job, error: `Cannot cancel job in ${job.status} state` };
  }
  return { ...job, status: "cancelled", updatedAt: new Date().toISOString() };
}

export function readHashMythVideoCapabilities(env: NodeJS.ProcessEnv = process.env): HashMythVideoCapabilities {
  return {
    supportedSources: [...HASHMYTH_VIDEO_SOURCES],
    supportedOutputs: ["mp4", "script", "narration", "captions", "scene_list", "visual_prompts"],
    maxDurationSeconds: Number(env.HASHMYTH_MAX_VIDEO_DURATION ?? 300),
    maxScenes: Number(env.HASHMYTH_MAX_SCENES ?? 20),
    rendererConfigured: Boolean(env.HASHMYTH_RENDERER_URL),
    payShConfigured: Boolean(env.PLATFORM_PAYSH_API_BASE_URL),
    acceptsArbitraryPrompt: true,
    supportsDocumentUpload: true
  };
}

export function hashMythVideoFromToken(input: {
  tokenAddress: string;
  network?: "solana" | "ethereum" | "base";
}): HashMythVideoJob {
  return prepareHashMythVideo({
    title: `Token Video: ${input.tokenAddress.slice(0, 12)}...`,
    sourcePrompt: `Token analysis for ${input.tokenAddress} on ${input.network ?? "solana"}`,
    source: "token",
    inputPayload: { tokenAddress: input.tokenAddress, network: input.network ?? "solana" }
  });
}

export function hashMythVideoFromWallet(input: {
  walletAddress: string;
  network?: "solana" | "ethereum" | "base";
}): HashMythVideoJob {
  return prepareHashMythVideo({
    title: `Wallet Video: ${input.walletAddress.slice(0, 12)}...`,
    sourcePrompt: `Wallet activity and intelligence for ${input.walletAddress}`,
    source: "wallet",
    inputPayload: { walletAddress: input.walletAddress, network: input.network ?? "solana" }
  });
}

export function hashMythVideoFromXProfile(input: { handle: string }): HashMythVideoJob {
  return prepareHashMythVideo({
    title: `X Profile Video: @${input.handle}`,
    sourcePrompt: `X/Twitter profile analysis and content summary for @${input.handle}`,
    source: "x_profile",
    inputPayload: { handle: input.handle }
  });
}

export function hashMythVideoFromMarketThesis(input: { thesisId: string; thesisTitle: string }): HashMythVideoJob {
  return prepareHashMythVideo({
    title: `Thesis Video: ${input.thesisTitle}`,
    sourcePrompt: `Market thesis visualization for ${input.thesisTitle}`,
    source: "market_thesis",
    inputPayload: { thesisId: input.thesisId }
  });
}

export function hashMythVideoFromResearchReport(input: { questId: string; reportTitle: string }): HashMythVideoJob {
  return prepareHashMythVideo({
    title: `Research Video: ${input.reportTitle}`,
    sourcePrompt: `Research report visualization for ${input.reportTitle}`,
    source: "research_report",
    inputPayload: { questId: input.questId }
  });
}

export function hashMythVideoFromSimulation(input: { simulationId: string; simulationTitle: string }): HashMythVideoJob {
  return prepareHashMythVideo({
    title: `Simulation Video: ${input.simulationTitle}`,
    sourcePrompt: `Physics simulation visualization for ${input.simulationTitle}`,
    source: "simulation",
    inputPayload: { simulationId: input.simulationId }
  });
}

export function hashMythVideoFromAdCampaign(input: { campaignId: string; campaignName: string }): HashMythVideoJob {
  return prepareHashMythVideo({
    title: `Ad Video: ${input.campaignName}`,
    sourcePrompt: `Ad campaign visualization for ${input.campaignName}`,
    source: "ad_campaign",
    inputPayload: { campaignId: input.campaignId }
  });
}

export function hashMythVideoFromScript(input: { title: string; script: string }): HashMythVideoJob {
  return prepareHashMythVideo({
    title: input.title,
    sourcePrompt: input.script,
    source: "script",
    inputPayload: { rawScript: input.script }
  });
}
