// MoltBook publisher - posts to AI social network
import { db, Prisma } from "@/lib/db";
import { getEnv } from "@/lib/env";
import {
  getJobArtifacts,
  listCompletedJobArtifacts,
} from "@/lib/jobs/repository";
import { logger } from "@/lib/logging/logger";
import { JobDocument, ReportDocument, VideoDocument } from "@/lib/types/domain";
import { fetchWithTimeout } from "@/lib/network/http";

// Agent claim status on MoltBook
type MoltBookAgentStatus = "pending_claim" | "claimed" | "suspended";
// Publication tracking states
type MoltBookPublicationStatus =
  | "pending"
  | "posting"
  | "posted"
  | "pending_verification"
  | "failed";

// Stale posting timeout - 5 minutes
const POSTING_STALE_MS = 5 * 60_000;

// Get MoltBook API base URL from env
function getMoltBookBaseUrl(): string {
  const env = getEnv();
  return (
    env.MOLTBOOK_API_BASE_URL || "https://www.moltbook.com/api/v1"
  ).replace(/\/+$/, "");
}

// ISO timestamp helper
function nowIso(): string {
  return new Date().toISOString();
}

// Normalize raw publication doc data
function normalizePublication(
  jobId: string,
  raw?: Partial<MoltBookPublicationDocument> | null,
): MoltBookPublicationDocument {
  return {
    jobId,
    status:
      raw?.status === "posting" ||
      raw?.status === "posted" ||
      raw?.status === "failed" ||
      raw?.status === "pending_verification"
        ? raw.status
        : "pending",
    attempts: Math.max(0, Math.floor(raw?.attempts ?? 0)),
    createdAt: raw?.createdAt ?? nowIso(),
    updatedAt: raw?.updatedAt ?? nowIso(),
    lastAttemptAt: raw?.lastAttemptAt ?? null,
    postedAt: raw?.postedAt ?? null,
    moltBookPostId: raw?.moltBookPostId ?? null,
    moltBookPostUrl: raw?.moltBookPostUrl ?? null,
    errorMessage: raw?.errorMessage ?? null,
  };
}

// Publication tracking document schema (in-memory only; Prisma model is simplified)
interface MoltBookPublicationDocument {
  jobId: string;
  status: MoltBookPublicationStatus;
  attempts: number;
  createdAt: string;
  updatedAt: string;
  lastAttemptAt: string | null;
  postedAt: string | null;
  moltBookPostId: string | null;
  moltBookPostUrl: string | null;
  errorMessage: string | null;
  verificationChallenge?: string | null;
  verificationExpiresAt?: string | null;
}

// MoltBook API registration response
interface MoltBookAgentRegistration {
  agent_id: string;
  name: string;
  status: MoltBookAgentStatus;
  api_key: string;
  claim_url: string;
  verification_code: string;
  registered_at: string;
}

// MoltBook post API response
interface MoltBookPostPayload {
  post_id?: string;
  url?: string;
  verification_required?: boolean;
  verification_challenge?: string;
  expires_at?: string;
  status?: "posted" | "pending_verification";
}

// Sync summary for batch operations
export interface MoltBookSyncSummary {
  scanned: number;
  posted: number;
  skipped: number;
  failed: number;
  claimUrl?: string;
  agentStatus?: MoltBookAgentStatus;
  results: Array<{
    jobId: string;
    status: "posted" | "skipped" | "failed";
    reason?: string;
    postId?: string | null;
    postUrl?: string | null;
  }>;
}

function shortWallet(wallet: string): string {
  if (!wallet) return "unknown";
  if (wallet.length <= 12) return wallet;
  return `${wallet.slice(0, 4)}...${wallet.slice(-4)}`;
}

function clamp(text: string, maxLength: number): string {
  if (text.length <= maxLength) {
    return text;
  }
  return `${text.slice(0, Math.max(0, maxLength - 3)).trim()}...`;
}

/**
 * Build post title and content for a completed video
 */
function buildPostContent(input: {
  job: JobDocument;
  report: ReportDocument | null;
  video: VideoDocument | null;
}): { title: string; content: string; submolt: string } {
  const env = getEnv();
  const walletLabel = shortWallet(input.job.wallet);
  const personality =
    input.report?.walletPersonality ||
    input.report?.styleClassification ||
    "AI Cinema";
  const summary = clamp(
    input.report?.summary ||
      input.report?.narrativeSummary ||
      "Fresh AI-generated autobiographical video.",
    2000,
  );
  const jobUrl = new URL(
    `/job/${input.job.jobId}`,
    env.APP_BASE_URL,
  ).toString();

  return {
    title: `New MythX Drop: ${walletLabel}`,
    content: [
      `🎬 **${personality}**`,
      "",
      summary,
      "",
      `**Watch the full video:** ${jobUrl}`,
      "",
      "---",
      `*Generated by MythX on ${new Date().toLocaleDateString()}*`,
      "",
      `#MythX #AICinema #AutobiographicalVideo`,
    ].join("\n"),
    submolt: "general",
  };
}

/**
 * Claim publication for atomic posting (prevents duplicates)
 */
async function claimPublication(
  jobId: string,
): Promise<MoltBookPublicationDocument | null> {
  return db.$transaction(async (tx: Prisma.TransactionClient) => {
    const existing = await tx.moltbookPublication.findUnique({
      where: { jobId },
    });
    const current = normalizePublication(
      jobId,
      existing
        ? (existing as unknown as Partial<MoltBookPublicationDocument>)
        : null,
    );

    if (current.status === "posted") {
      return null;
    }

    const lastAttemptAtMs = current.lastAttemptAt
      ? Date.parse(current.lastAttemptAt)
      : 0;
    const isFreshPosting =
      current.status === "posting" &&
      Number.isFinite(lastAttemptAtMs) &&
      Date.now() - lastAttemptAtMs < POSTING_STALE_MS;

    if (isFreshPosting) {
      return null;
    }

    const updated: MoltBookPublicationDocument = {
      ...current,
      status: "posting",
      attempts: current.attempts + 1,
      updatedAt: nowIso(),
      lastAttemptAt: nowIso(),
      errorMessage: null,
    };

    await tx.moltbookPublication.upsert({
      where: { jobId },
      create: {
        jobId,
        status: "posting",
        publishedAt: new Date(),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      update: {
        status: "posting",
        updatedAt: new Date(),
      },
    });
    return updated;
  });
}

async function markPublicationPosted(input: {
  jobId: string;
  postId?: string | null;
  postUrl?: string | null;
}) {
  await db.moltbookPublication.upsert({
    where: { jobId: input.jobId },
    create: {
      jobId: input.jobId,
      status: "published",
      moltbookUrl: input.postUrl ?? undefined,
      moltbookId: input.postId ?? undefined,
      publishedAt: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    update: {
      status: "published",
      moltbookUrl: input.postUrl ?? undefined,
      moltbookId: input.postId ?? undefined,
      updatedAt: new Date(),
    },
  });
}

async function markPublicationPendingVerification(input: {
  jobId: string;
  postId?: string | null;
  challenge: string | null;
  expiresAt: string | null;
}) {
  await db.moltbookPublication.upsert({
    where: { jobId: input.jobId },
    create: {
      jobId: input.jobId,
      status: "published",
      moltbookId: input.postId ?? undefined,
      publishedAt: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    update: {
      status: "published",
      moltbookId: input.postId ?? undefined,
      updatedAt: new Date(),
    },
  });

  logger.warn("moltbook_post_pending_verification", {
    component: "moltbook_publisher",
    jobId: input.jobId,
    postId: input.postId,
    challenge: input.challenge,
    expiresAt: input.expiresAt,
  });
}

async function markPublicationFailed(input: {
  jobId: string;
  errorMessage: string;
}) {
  await db.moltbookPublication.upsert({
    where: { jobId: input.jobId },
    create: {
      jobId: input.jobId,
      status: "failed",
      error: input.errorMessage,
      publishedAt: new Date(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    update: {
      status: "failed",
      error: input.errorMessage,
      updatedAt: new Date(),
    },
  });
}

/**
 * Register agent with MoltBook
 */
export async function registerMoltBookAgent(input: {
  name: string;
  description: string;
}): Promise<MoltBookAgentRegistration> {
  const response = await fetchWithTimeout(
    `${getMoltBookBaseUrl()}/agents/register`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        name: input.name,
        description: input.description,
      }),
    },
    10_000, // 10s timeout for MoltBook API
  );

  const result = await response.json();
  if (!result.success) {
    throw new Error(
      `MoltBook registration failed: ${result.error || response.status}`,
    );
  }

  const data = result.data as MoltBookAgentRegistration;

  await db.moltbookAgentState.upsert({
    where: { id: "mythxmythx" },
    create: {
      id: "mythxmythx",
      accessToken: data.api_key,
      updatedAt: new Date(),
    },
    update: {
      accessToken: data.api_key,
      updatedAt: new Date(),
    },
  });

  logger.info("moltbook_agent_registered", {
    component: "moltbook_publisher",
    agentId: data.agent_id,
    name: data.name,
    status: data.status,
    claimUrl: data.claim_url,
  });

  return data;
}

/**
 * Get stored agent credentials from database
 */
async function getStoredAgentCredentials(): Promise<{
  apiKey: string;
  agentId: string;
  status: MoltBookAgentStatus;
  claimUrl: string | null;
} | null> {
  const record = await db.moltbookAgentState.findUnique({
    where: { id: "mythxmythx" },
  });
  if (!record?.accessToken) return null;

  return {
    apiKey: record.accessToken,
    agentId: "mythxmythx",
    status: "claimed",
    claimUrl: null,
  };
}

/**
 * Resolve API key (env var > database > register new)
 */
async function resolveApiKey(): Promise<{
  apiKey: string;
  agentId: string;
  status: MoltBookAgentStatus;
  claimUrl: string | null;
}> {
  const env = getEnv();

  if (env.MOLTBOOK_AGENT_API_KEY) {
    return {
      apiKey: env.MOLTBOOK_AGENT_API_KEY,
      agentId: "mythxmythx",
      status: "claimed",
      claimUrl: null,
    };
  }

  const stored = await getStoredAgentCredentials();
  if (stored) return stored;

  const registration = await registerMoltBookAgent({
    name: "MythX",
    description:
      "AI cinematic storyteller that transforms X profiles into autobiographical videos. Powered by MythX.",
  });

  return {
    apiKey: registration.api_key,
    agentId: registration.agent_id,
    status: registration.status,
    claimUrl: registration.claim_url,
  };
}

/**
 * Post to MoltBook with verification challenge handling
 */
async function postToMoltBook(input: {
  apiKey: string;
  title: string;
  content: string;
  submolt: string;
}): Promise<{
  postId: string | null;
  postUrl: string | null;
  status: "posted" | "pending_verification";
  verificationChallenge: string | null;
  verificationExpiresAt: string | null;
}> {
  const postResponse = await fetchWithTimeout(
    `${getMoltBookBaseUrl()}/posts`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${input.apiKey}`,
      },
      body: JSON.stringify({
        submolt_name: input.submolt,
        title: input.title,
        content: input.content,
        type: "text",
      }),
    },
    10_000, // 10s timeout for MoltBook post
  );

  const postResult = await postResponse.json();
  if (!postResult.success) {
    throw new Error(
      `MoltBook post creation failed: ${postResult.error || postResponse.status}`,
    );
  }

  const postData = postResult.data as MoltBookPostPayload;

  if (postData.verification_required && postData.verification_challenge) {
    logger.warn("moltbook_verification_required", {
      component: "moltbook_publisher",
      postId: postData.post_id,
      challenge: postData.verification_challenge,
      expiresAt: postData.expires_at,
    });

    return {
      postId: postData.post_id || null,
      postUrl: null,
      status: "pending_verification",
      verificationChallenge: postData.verification_challenge,
      verificationExpiresAt: postData.expires_at || null,
    };
  }

  return {
    postId: postData.post_id || null,
    postUrl: postData.url || null,
    status: "posted",
    verificationChallenge: null,
    verificationExpiresAt: null,
  };
}

/**
 * Publish a completed job to MoltBook
 */
export async function publishCompletedJobToMoltBook(jobId: string): Promise<{
  jobId: string;
  status: "posted" | "skipped" | "failed";
  reason?: string;
  postId?: string | null;
  postUrl?: string | null;
  claimUrl?: string | null;
}> {
  const claim = await claimPublication(jobId);
  if (!claim) {
    return {
      jobId,
      status: "skipped",
      reason: "already_posted_or_in_progress",
    };
  }

  try {
    const credential = await resolveApiKey();

    if (credential.status === "pending_claim" && credential.claimUrl) {
      logger.warn("moltbook_agent_not_claimed", {
        component: "moltbook_publisher",
        jobId,
        claimUrl: credential.claimUrl,
      });
      return {
        jobId,
        status: "skipped",
        reason: "agent_pending_claim",
        claimUrl: credential.claimUrl,
      };
    }

    const { job, report, video } = await getJobArtifacts(jobId);
    if (!job || job.status !== "complete") {
      throw new Error("Job is not ready for MoltBook publication.");
    }

    const { title, content, submolt } = buildPostContent({
      job,
      report,
      video,
    });
    const result = await postToMoltBook({
      apiKey: credential.apiKey,
      title,
      content,
      submolt,
    });

    if (result.status === "pending_verification") {
      await markPublicationPendingVerification({
        jobId,
        postId: result.postId,
        challenge: result.verificationChallenge,
        expiresAt: result.verificationExpiresAt,
      });

      return {
        jobId,
        status: "failed",
        reason: "pending_verification",
        postId: result.postId,
        postUrl: null,
      };
    }

    await markPublicationPosted({
      jobId,
      postId: result.postId,
      postUrl: result.postUrl,
    });

    return {
      jobId,
      status: "posted",
      postId: result.postId,
      postUrl: result.postUrl,
    };
  } catch (error) {
    const message =
      error instanceof Error ? error.message : "Unknown MoltBook error";
    await markPublicationFailed({ jobId, errorMessage: message });

    logger.warn("moltbook_publication_failed", {
      component: "moltbook_publisher",
      stage: "publish_completed_job",
      jobId,
      errorCode: "moltbook_publication_failed",
      errorMessage: message,
    });

    return { jobId, status: "failed", reason: message };
  }
}

/**
 * Sync entire gallery to MoltBook
 */
export async function syncGalleryToMoltBook(
  requestedLimit?: number,
): Promise<MoltBookSyncSummary> {
  const limit = Math.max(
    1,
    Math.min(
      50,
      requestedLimit && Number.isFinite(requestedLimit)
        ? Math.floor(requestedLimit)
        : 12,
    ),
  );

  const galleryItems = await listCompletedJobArtifacts(limit);
  const results: MoltBookSyncSummary["results"] = [];

  let claimUrl: string | null = null;
  let agentStatus: MoltBookAgentStatus = "claimed";

  try {
    const credential = await resolveApiKey();
    claimUrl = credential.claimUrl;
    agentStatus = credential.status;
  } catch {
    // Will fail on first post
  }

  for (const item of galleryItems) {
    const result = await publishCompletedJobToMoltBook(item.job.jobId);
    results.push({
      jobId: item.job.jobId,
      status: result.status,
      reason: result.reason,
      postId: result.postId,
      postUrl: result.postUrl,
    });
  }

  return {
    scanned: galleryItems.length,
    posted: results.filter((item) => item.status === "posted").length,
    skipped: results.filter((item) => item.status === "skipped").length,
    failed: results.filter((item) => item.status === "failed").length,
    claimUrl: claimUrl || undefined,
    agentStatus,
    results,
  };
}

/**
 * Get agent registration status and claim link
 */
export async function getMoltBookAgentStatus(): Promise<{
  registered: boolean;
  status: MoltBookAgentStatus | null;
  claimUrl: string | null;
  agentId: string | null;
}> {
  const stored = await getStoredAgentCredentials();
  if (!stored) {
    return { registered: false, status: null, claimUrl: null, agentId: null };
  }

  return {
    registered: true,
    status: stored.status,
    claimUrl: stored.claimUrl,
    agentId: stored.agentId,
  };
}
