import type { VisualMetaphorEntry } from "@/lib/cinema/types";

export const VISUAL_METAPHOR_LIBRARY: VisualMetaphorEntry[] = [
  {
    id: "roulette_cathedral_wager",
    triggerTags: ["gambler", "casino", "temptation", "wager", "opening"],
    characterArcCompatibility: ["villain", "fallen_hero", "jester", "trickster"],
    environment: "a casino-cathedral where stained glass is made of token icons and roulette shadows",
    symbolicObjects: ["roulette wheel", "casino chips like relics", "candles beside a keyboard"],
    lighting: "golden highlights with green-red contrast, smoke shafts through arches",
    colorPalette: ["casino gold", "neon green", "warning red", "ink black"],
    motionStyle: "slow push-in that accelerates into snap-zooms when stakes rise",
    soundStyle: "chip clacks, distant crowd murmur, heartbeat bass swelling",
    promptLanguageHints: ["the first wager", "high-stakes neon prayer", "the house listens"],
  },
  {
    id: "revenge_trading_boxing_ring",
    triggerTags: ["revenge", "rematch", "impact", "villain_turn", "damage"],
    characterArcCompatibility: ["villain", "fallen_hero", "trickster"],
    environment: "a brutal boxing ring inside a neon casino, ropes vibrating like chart lines",
    symbolicObjects: ["bloodied hand wraps", "a bell that sounds like a trade fill", "sweat on canvas"],
    lighting: "hard top light, red-green strobe, smoke drifting under spotlights",
    colorPalette: ["warning red", "sickly neon green", "ink black", "chrome"],
    motionStyle: "handheld ringside tracking, punchy snap-zooms, impact cuts",
    soundStyle: "impact-heavy hits, crowd roar turning into glitch noise, heartbeat bass",
    promptLanguageHints: ["rematch energy", "no-cooldown decision", "the bell demands another round"],
  },
  {
    id: "diamond_hands_warrior",
    triggerTags: ["diamond_hands", "conviction", "martyr", "hero", "holding"],
    characterArcCompatibility: ["hero", "martyr", "survivor"],
    environment: "a lone warrior on a battlefield, holding a shield etched with a memecoin sigil",
    symbolicObjects: ["a chipped shield", "embers in the air", "a banner made of torn posters"],
    lighting: "sunset backlight through dust, warm rim light, long shadows",
    colorPalette: ["sunset gold", "battlefield umber", "embers orange", "storm blue"],
    motionStyle: "slow heroic dolly, low-angle push-ins, steady composition",
    soundStyle: "distant war drums, wind through armor, orchestral rise under restraint",
    promptLanguageHints: ["stoic pressure", "earned resolve", "holding is a stance"],
  },
  {
    id: "fomo_train_departure",
    triggerTags: ["fomo", "chase", "train", "momentum", "temptation"],
    characterArcCompatibility: ["fallen_hero", "villain", "trickster", "pilgrim"],
    environment: "a rain-soaked train platform where neon departure boards flicker with token symbols",
    symbolicObjects: ["a departure board that glitches", "wet footsteps", "a ticket stamped with a memecoin icon"],
    lighting: "neon reflections on wet concrete, harsh backlight through steam",
    colorPalette: ["neon cyan", "station amber", "wet asphalt black", "electric magenta"],
    motionStyle: "running tracking shot, whip pans to the departure board, motion blur",
    soundStyle: "distant train horn, sprinting breaths, siren-like market tension",
    promptLanguageHints: ["missed timing", "sprinting toward the candle", "the doors almost close"],
  },
  {
    id: "bagholding_empty_casino",
    triggerTags: ["bagholding", "martyr", "aftermath", "loss", "shrines"],
    characterArcCompatibility: ["martyr", "ghost", "fallen_hero"],
    environment: "an abandoned neon casino at sunrise, slot machines humming with no players",
    symbolicObjects: ["a dead roulette wheel", "token posters peeling off pillars", "coins on a velvet table"],
    lighting: "cold sunrise through dusty windows, neon dying in the corners",
    colorPalette: ["washed gold", "dead neon pink", "pale morning blue", "dust gray"],
    motionStyle: "slow creeping steadicam, long takes, static wide shots",
    soundStyle: "hollow room tone, distant ventilation hum, faint casino chimes glitching out",
    promptLanguageHints: ["denial", "emptiness", "the house is quiet now"],
  },
  {
    id: "breakout_rocket_launch",
    triggerTags: ["breakout", "rocket", "comeback", "climax", "victory"],
    characterArcCompatibility: ["hero", "survivor", "prophet"],
    environment: "a rocket launch pad on a cyberpunk skyline, token iconography reflected in the ignition glow",
    symbolicObjects: ["a countdown tower made of screens", "a rocket branded like a meme poster", "sparks raining"],
    lighting: "white-hot ignition flare, green-blue rim light, smoke illuminated from below",
    colorPalette: ["ignition white", "neon green", "storm blue", "metallic silver"],
    motionStyle: "crane rise into the sky, steady cinematic tracking, slow-motion debris",
    soundStyle: "engine roar, orchestral swell, sub-bass pressure release",
    promptLanguageHints: ["pressure release", "earned lift-off", "the skyline watches"],
  },
  {
    id: "late_night_neon_city",
    triggerTags: ["goblin_hour", "neon", "trench", "opening", "discovery"],
    characterArcCompatibility: [
      "villain",
      "fallen_hero",
      "jester",
      "trickster",
      "survivor",
      "hero",
      "pilgrim",
      "ghost",
      "prophet",
      "martyr",
    ],
    environment: "a 3AM cyberpunk city, rain and flickering screens, alleyways lined with token billboards",
    symbolicObjects: ["flickering billboards", "wet neon reflections", "a hooded silhouette under screen glow"],
    lighting: "street neon, screen flicker, fog diffusion",
    colorPalette: ["neon teal", "chart green", "warning red", "midnight purple"],
    motionStyle: "smooth tracking through alleys, shallow depth of field, occasional snap-zooms",
    soundStyle: "rain on glass, distant thunder, keyboard clicks under synth tension",
    promptLanguageHints: ["goblin hour energy", "dangerous optimism", "the city breathes like a market"],
  },
  {
    id: "collapse_storm_bridge",
    triggerTags: ["collapse", "storm", "damage", "villain_turn", "failure"],
    characterArcCompatibility: ["villain", "fallen_hero", "trickster"],
    environment: "a bridge collapsing in a lightning storm, screens shattering like glass",
    symbolicObjects: ["cracked monitors", "falling neon signage", "a rope fraying mid-sprint"],
    lighting: "strobe lightning, harsh blue flashes, red warning beacons",
    colorPalette: ["storm blue", "warning red", "electric white", "soot black"],
    motionStyle: "aggressive handheld, dutch angles, debris in slow motion",
    soundStyle: "distant thunder, metal tearing, glitching alarms",
    promptLanguageHints: ["unstable world", "no safe footing", "gravity as consequence"],
  },
  {
    id: "comeback_sunrise_battlefield",
    triggerTags: ["comeback", "sunrise", "survivor", "resolution", "after_damage"],
    characterArcCompatibility: ["hero", "survivor", "martyr", "prophet"],
    environment: "dawn after battle, fog rolling over a ruined plaza of screens and banners",
    symbolicObjects: ["a torn banner with a token sigil", "embers on wet stone", "a single upright chair"],
    lighting: "soft sunrise, warm haze, gentle lens flare",
    colorPalette: ["sunrise peach", "smoke gray", "soft gold", "cool slate"],
    motionStyle: "steady dolly forward, slow pans, breathing room between cuts",
    soundStyle: "morning ambience, distant sirens, a calm heartbeat bass fading out",
    promptLanguageHints: ["weary victory", "earned calm", "survival is the ending"],
  },
  {
    id: "jester_funhouse_market",
    triggerTags: ["jester", "funhouse", "absurd", "luck", "comic_chaos"],
    characterArcCompatibility: ["jester", "trickster"],
    environment: "a distorted carnival funhouse where mirrors warp token mascots into monsters and clowns",
    symbolicObjects: ["warped mirrors", "prize wheels", "balloons that flicker into charts"],
    lighting: "saturated neon, spinning spotlights, strobe bursts",
    colorPalette: ["carnival pink", "acid green", "electric blue", "ink black"],
    motionStyle: "spinning gimbal shots, rapid zooms, comedic whip pans",
    soundStyle: "broken calliope melody, laugh-echo reverb, glitch percussion",
    promptLanguageHints: ["surreal momentum", "darkly funny", "the market is a prank"],
  },
  {
    id: "ghost_empty_trading_floor",
    triggerTags: ["ghost", "empty", "quiet", "aftermath", "detached"],
    characterArcCompatibility: ["ghost", "martyr", "pilgrim"],
    environment: "a silent trading floor with dim monitors, blue haze, dust floating in projector light",
    symbolicObjects: ["unattended monitors", "a coffee cup ring", "a chair that slowly spins"],
    lighting: "cold blue haze, minimal practicals, soft screen glow",
    colorPalette: ["deep blue", "steel gray", "pale cyan", "shadow black"],
    motionStyle: "slow glide, locked-off frames, minimal movement",
    soundStyle: "hollow room tone, electric hum, distant rain",
    promptLanguageHints: ["presence without confession", "quiet ruin", "the night lingers"],
  },
  {
    id: "altar_of_hopium",
    triggerTags: ["believer", "shrine", "conviction", "first_conviction"],
    characterArcCompatibility: ["martyr", "prophet", "hero", "pilgrim"],
    environment: "a candle-lit shrine built from posters, stickers, and shattered phone screens",
    symbolicObjects: ["candles", "a token icon as an altar piece", "notes pinned like prophecies"],
    lighting: "warm candlelight fighting cold monitor glow",
    colorPalette: ["candle gold", "screen cyan", "smoke gray", "deep black"],
    motionStyle: "slow push-in, macro close-ups, reverent framing",
    soundStyle: "soft bells, low choir pad, faint keyboard clicks",
    promptLanguageHints: ["faith under pressure", "ritual of hope", "vows in the dark"],
  },
  {
    id: "alchemist_neon_lab",
    triggerTags: ["alchemist", "lab", "transformation", "pivot"],
    characterArcCompatibility: ["hero", "prophet", "trickster", "survivor"],
    environment: "a neon alchemy lab with glass beakers reflecting token holograms in liquid light",
    symbolicObjects: ["beakers", "glowing reagents", "a notebook of symbols"],
    lighting: "bioluminescent glow, crisp highlights, smoke wisps",
    colorPalette: ["neon green", "ultraviolet", "silver", "black"],
    motionStyle: "precise macro shots, slow orbit, controlled camera moves",
    soundStyle: "electric hum, glass clinks, suspenseful synth bed",
    promptLanguageHints: ["turn chaos into meaning", "reaction goes unstable", "transformation"],
  },
  {
    id: "prophet_observatory",
    triggerTags: ["prophet", "omens", "discovery", "constellations"],
    characterArcCompatibility: ["prophet", "hero", "pilgrim"],
    environment: "an observatory where charts become constellations and token icons drift like moons",
    symbolicObjects: ["telescope", "star map charts", "floating glyphs"],
    lighting: "moonlit blue with prismatic highlights",
    colorPalette: ["moon blue", "starlight white", "neon teal", "shadow black"],
    motionStyle: "slow crane, celestial parallax, calm push-ins",
    soundStyle: "choir pads, distant thunder, sub-bass prophecy hum",
    promptLanguageHints: ["uncanny timing", "the sky whispers", "omens resolve"],
  },
  {
    id: "wanted_poster_alley",
    triggerTags: ["trench_lore", "alley", "posters", "billboards"],
    characterArcCompatibility: ["villain", "hero", "jester", "trickster", "fallen_hero", "survivor"],
    environment: "a neon alley packed with wanted posters and hologram billboards of meme mascots",
    symbolicObjects: ["wanted posters", "hologram billboards", "spray paint and torn tape"],
    lighting: "flickering signage, rim-lit fog, projector beams",
    colorPalette: ["neon cyan", "warning red", "dirty gold", "asphalt black"],
    motionStyle: "tracking past posters, rack focus between icons, quick inserts",
    soundStyle: "street rain, distant sirens, low synth tension",
    promptLanguageHints: ["trench lore", "the city keeps receipts", "posters as prophecy"],
  },
  {
    id: "mirror_maze_pivot",
    triggerTags: ["trickster", "mirrors", "pivot", "reversal"],
    characterArcCompatibility: ["trickster", "jester", "fallen_hero"],
    environment: "a mirror maze where token icons multiply and distort into false exits",
    symbolicObjects: ["fractured reflections", "exit signs pointing wrong", "shards of glass like pixels"],
    lighting: "strobing neon, hard reflections, prismatic flares",
    colorPalette: ["electric magenta", "neon teal", "white glare", "black void"],
    motionStyle: "fast turns, dutch angles, dizzying spins",
    soundStyle: "rubber-band snaps, glitch percussion, laugh-echo reverb",
    promptLanguageHints: ["every door is a trap", "reversal energy", "rules dissolve"],
  },
  {
    id: "throne_of_broken_screens",
    triggerTags: ["villain", "overconfidence", "crown", "escalation"],
    characterArcCompatibility: ["villain", "fallen_hero"],
    environment: "a throne built from broken screens and casino gold, token icons like stained glass",
    symbolicObjects: ["a crown of cables", "shattered monitors", "gold dust falling"],
    lighting: "harsh gold highlights with red underglow",
    colorPalette: ["casino gold", "warning red", "soot black", "neon green"],
    motionStyle: "slow ominous push-in, low angles, oppressive framing",
    soundStyle: "low brass rumble, distorted crowd murmurs, sub-bass threat",
    promptLanguageHints: ["greed as religion", "the throne demands tribute", "delusion of control"],
  },
  {
    id: "bunker_radio_survivor",
    triggerTags: ["survivor", "bunker", "after_damage", "stabilize"],
    characterArcCompatibility: ["survivor", "hero"],
    environment: "a concrete bunker with a crackling radio, token posters taped to the walls like maps",
    symbolicObjects: ["a radio", "duct tape", "paper maps made of stickers"],
    lighting: "single overhead bulb, warm practical light against cold screen glow",
    colorPalette: ["warm amber", "cold blue", "concrete gray", "shadow black"],
    motionStyle: "steady handheld, close-up breathing shots, grounded movement",
    soundStyle: "radio static, distant sirens, steady heartbeat bass",
    promptLanguageHints: ["stabilize", "escape route", "endurance"],
  },
  {
    id: "paper_hands_blizzard",
    triggerTags: ["panic", "paper_hands", "damage", "fear", "flight"],
    characterArcCompatibility: ["fallen_hero", "villain", "survivor"],
    environment: "a blizzard of shredded paper posters and receipts whipping through a neon street",
    symbolicObjects: ["paper scraps like snow", "a shaking hand over a phone", "sirens reflecting on wet asphalt"],
    lighting: "harsh street neon with cold blue flashes",
    colorPalette: ["ice blue", "neon red", "wet black", "white glare"],
    motionStyle: "shaky close-ups, fast tracking, frantic cuts",
    soundStyle: "wind howl, breath in mic, distant alarms",
    promptLanguageHints: ["panic exit energy", "flight response", "the city turns cold"],
  },
  {
    id: "neon_rooftop_sprint",
    triggerTags: ["chase", "fomo", "momentum", "run", "escalation"],
    characterArcCompatibility: ["fallen_hero", "villain", "trickster", "survivor"],
    environment: "neon rooftops under rain, the protagonist sprinting between glowing billboards",
    symbolicObjects: ["billboard reflections", "a red exit sign", "a token mascot looming like an ad"],
    lighting: "rain reflections, saturated signage, sharp rim light",
    colorPalette: ["neon cyan", "chart green", "warning red", "midnight black"],
    motionStyle: "high-speed tracking, slow-motion leaps, whip pans",
    soundStyle: "rain on metal, fast hi-hats, siren-like market tension",
    promptLanguageHints: ["sprinting toward the move", "no time to breathe", "doors closing"],
  },
  {
    id: "subway_tunnel_reentry",
    triggerTags: ["reentry", "revenge", "underground", "pivot"],
    characterArcCompatibility: ["villain", "fallen_hero", "trickster"],
    environment: "an underground subway tunnel where token posters flash by like warnings",
    symbolicObjects: ["strobing tunnel lights", "a train of screens", "graffiti arrows pointing nowhere"],
    lighting: "staccato overhead lights, green-red flicker, steam",
    colorPalette: ["dirty green", "warning red", "steel gray", "shadow black"],
    motionStyle: "running POV, rhythmic cuts, relentless forward motion",
    soundStyle: "train rumble, rhythmic clacks, bass thumps like a pulse",
    promptLanguageHints: ["rapid re-entry", "no cooldown", "the tunnel pulls you forward"],
  },
  {
    id: "digital_funeral_procession",
    triggerTags: ["aftermath", "martyr", "ghost", "ruin", "acceptance"],
    characterArcCompatibility: ["martyr", "ghost", "fallen_hero"],
    environment: "a quiet funeral procession of hologram posters dissolving into morning fog",
    symbolicObjects: ["hologram banners", "candles in puddles", "a coin talisman left behind"],
    lighting: "soft sunrise through haze, dim neon dying out",
    colorPalette: ["pale gold", "smoke gray", "cold blue", "shadow black"],
    motionStyle: "slow glides, lingering close-ups, minimal movement",
    soundStyle: "hollow room tone, low cello grief, distant city ambience",
    promptLanguageHints: ["quiet ruin", "acceptance", "the posters fade"],
  },
  {
    id: "chessboard_trading_table",
    triggerTags: ["discipline", "precision", "hero", "prophet", "control"],
    characterArcCompatibility: ["hero", "prophet", "survivor"],
    environment: "a trading desk that becomes a chessboard, pieces lit by monitor glow",
    symbolicObjects: ["chess knight", "metronome", "a pen marking invisible lines"],
    lighting: "controlled hard light, clean shadows, calm highlights",
    colorPalette: ["cool slate", "neon green", "white glare", "ink black"],
    motionStyle: "steady dolly, slow macro inserts, deliberate framing",
    soundStyle: "metronome ticks, soft keyboard clicks, low synth bed",
    promptLanguageHints: ["patience as power", "controlled sizing without saying numbers", "move with intent"],
  },
  {
    id: "liquidity_desert_mirage",
    triggerTags: ["pilgrim", "search", "mirage", "uncertain", "journey"],
    characterArcCompatibility: ["pilgrim", "ghost", "martyr"],
    environment: "a desert of glowing sand where distant billboards shimmer like mirages",
    symbolicObjects: ["a compass made of a token icon", "footprints in neon dust", "a far-off sign flickering"],
    lighting: "bleached sunrise with cold neon underglow",
    colorPalette: ["sand gold", "neon teal", "pale blue", "shadow black"],
    motionStyle: "long lens shots, slow pans, wide lonely frames",
    soundStyle: "wind, distant hum, soft morning ambience",
    promptLanguageHints: ["searching", "hope and confusion", "the sign keeps moving"],
  },
  {
    id: "arcade_token_marquee",
    triggerTags: ["jester", "trench_lore", "arcade", "mascot", "posters"],
    characterArcCompatibility: ["jester", "trickster", "villain"],
    environment: "an arcade street where token mascots glow on marquee signs and prize wheels",
    symbolicObjects: ["arcade cabinets", "marquee signage", "tickets spilling like confetti"],
    lighting: "saturated neon, spinning spotlights, reflected glow",
    colorPalette: ["electric blue", "carnival pink", "acid green", "ink black"],
    motionStyle: "fast inserts, comedic whip pans, spinning camera reveals",
    soundStyle: "arcade bleeps, broken calliope, glitch percussion",
    promptLanguageHints: ["the market is a game", "absurd signage", "dark humor"],
  },
  {
    id: "stormglass_control_room",
    triggerTags: ["survivor", "stabilize", "control_room", "after_damage"],
    characterArcCompatibility: ["survivor", "hero"],
    environment: "a control room of storm glass windows, charts reflected like weather systems",
    symbolicObjects: ["storm glass", "radio headset", "a map of lights"],
    lighting: "cool practicals, storm flashes outside, calm interior light",
    colorPalette: ["storm blue", "cool gray", "neon green", "white glare"],
    motionStyle: "steady handheld, grounded shots, slow push-ins on breathing",
    soundStyle: "wind outside, radio clicks, heartbeat bass stabilizing",
    promptLanguageHints: ["hold the line", "stabilize", "survive the weather"],
  },
  {
    id: "oracle_rune_server_room",
    triggerTags: ["prophet", "omens", "server_room", "symbols", "discovery"],
    characterArcCompatibility: ["prophet", "hero", "trickster"],
    environment: "a server room where token glyphs crawl across cables like runes",
    symbolicObjects: ["glowing cables", "rune-like token icons", "a notebook of symbols"],
    lighting: "cold blue LEDs with prismatic flicker",
    colorPalette: ["cold blue", "neon teal", "silver", "shadow black"],
    motionStyle: "slow tracking between racks, macro close-ups, calm reveals",
    soundStyle: "electric hum, distant bells, low synth prophecy",
    promptLanguageHints: ["omens in circuitry", "uncanny foresight", "the room whispers"],
  },
];
