export const disclosureParagraphs: string[] = [
  'HYPERMYTHS DISCLOSURE: GAMIFIED INTERNET CAPITAL MARKET WORLDS FOR HUMANS & AGENTS',
  '1. Purpose',
  'This disclosure is published before the launch of $pMYTH and $bMYTH to explain the intended structure, purpose, risks, limits, mechanics, governance scope and experimental nature of the HyperMyths ecosystem.',
  'This disclosure is not investment advice, tax advice, trading advice, financial advice, accounting advice, medical advice, scientific advice, research advice or individualized legal advice to any purchaser, holder, staker, trader, contributor, developer, researcher, tester, creator, player, faction member or community participant.',
  'HyperMyths should be understood as an experimental MMO alternate reality game layered across token communities, AI media generation, internet capital markets, synthetic data generation quests, prediction markets, computation markets, autonomous agents, advertising systems, creator attention markets, governance experiments, research simulations and world-building.',
  'There is currently no corporation, company, foundation, association, DAO legal wrapper, formal legal entity, registered issuer, fund, clinic, hospital, laboratory, research institution, medical organization or scientific institution behind HyperMyths, $pMYTH or $bMYTH unless a separate public announcement says otherwise.',
  'There is only a single pseudonymous human operator and near-autonomous agents experimenting with software, agents, media, games, token communities, public internet markets, synthetic data generation, research quests, computation markets and world-building.',
  'No person should assume that there is a company treasury, board, management team, employee base, formal issuer, registered entity, audited balance sheet, corporate governance structure, clinical sponsor, scientific institution or legal organization behind the project.',
  'Participation should be based only on a willingness to use, test, build, play, research, generate synthetic data, experiment and accept the possibility of total loss.',
  'This disclosure has two parts. The first part is aasimog short 42-point summary written in simple language for quick reading. The second part is the detailed 42-point disclosure, which explains the same topics in longer form with more risk language, limitations and context.',
  'The short 42-point summary is only a simplified guide. It does not replace the detailed disclosure. If there is any conflict, inconsistency, omission, ambiguity or difference between the short summary and the detailed disclosure, the detailed disclosure controls and supersedes the short summary.',
  'If we knew what it was we were doing, it would not be called research, would it? -Albert Einstein',
  "This is an experiment. If everything was already known, stable, safe, clear and guaranteed, it would not be research, and it would not be a game. This was built for the kind of retard who looks at a 70% drawdown & thinks: GOOD! CHEAPER BAGS! That's the kind of retard bitcoin & crypto was built for. That's the kind of retard who makes it.",
  'Any person who participates does so voluntarily and at their own risk. The tokens may be volatile, illiquid, manipulated, technically defective, economically unsuccessful, legally restricted or worthless. The software may fail. The agents may fail. The games may fail. The launchpads may change rules. The markets may behave irrationally. The project may change. Participation should be based only on a willingness to use, test, build, play, experiment and accept the possibility of total loss.',
  '2. Project Overview & Not Advice',
  'Behind it all is surely an idea so simple, so beautiful, that when we grasp it — in a decade, a century, or a millennium — we will all say to each other, how could it have been otherwise? How could we have been so stupid?',
  '-John Archibald Wheeler',
  'HyperMyths is an experimental ecosystem for gamified internet capital markets, MMO alternate reality gameplay, AI media generation, token-community gaming, advertising, creator attention markets, prediction markets, computation markets, autonomous agents, open-source software testing, model testing, research coordination, governance experimentation, capital-management experiments, talent-management experiments, cancer synthetic data generation quests, physics synthetic data generation quests and community world creation.',
  'The basic idea is that token communities can become playable factions rather than passive groups of spectators watching a chart.',
  'A token community may generate media, create lore, buy ads, test models, run prediction markets, price computation, participate in faction governance, launch a game world, test open-source software, train or evaluate agents, route attention, coordinate creators, test capital allocation, test talent coordination, generate synthetic datasets, complete daily tasks and compete in weekly seasons.',
  'HyperMyths is intended to make community attention productive. Attention can become media. Media can become ads. Ads can become distribution. Distribution can become game activity. Game activity can become prediction markets. Prediction markets can become information. Information can become research. Research can become synthetic data generation. Synthetic data can become model testing. Model testing can become software improvement. Software improvement can become more worlds. More worlds can create more faction activity.',
  'Faction activity may create demand for computation, creative labor, agent operations, capital management, prediction, research review, data generation, simulation and attention routing.',
  'This is the experiment.',
  'The project is not presented as a stable product, mature financial system, regulated fund, investment company, broker, exchange, casino, bank, asset manager, talent agency, registered investment adviser, commodity trading adviser, medical provider, scientific institution, clinical trial sponsor or guaranteed income system.',
  'It is experimental beta software and experimental community infrastructure framed as an MMO alternate reality game.',
  '3. Preliminary Risk Statement',
  'Participation is highly risky.',
  'No person should buy, hold, stake, vote with, transfer, bridge, trade or use $pMYTH or $bMYTH with funds they cannot afford to lose.',
  'The tokens may go to zero. The websites may break. The servers may fail. The game may fail. The agents may hallucinate. The markets may be manipulated. The launchpads may change their rules. Smart contracts may fail. Prediction markets may resolve incorrectly. Computation markets may misprice work. Synthetic data generation quests may produce bad data. AI systems may generate inaccurate or misleading content. Advertising may fail. Community attention may disappear.',
  'No person should confuse a game mechanic with financial safety.',
  'No person should confuse token governance with corporate governance.',
  'No person should confuse synthetic data generation with real medical evidence or real scientific evidence.',
  'No person should confuse research simulations with clinical proof, peer review, laboratory validation or investment alpha.',
  'No person should confuse token ownership with ownership of software, agents, patents, treasury, websites, research, models, data, synthetic datasets or future business value.',
  'HyperMyths may be fun, useful, chaotic, educational, entertaining or productive. It may also fail completely.',
  '4. Single Operator Experiment',
  'The project is operated by a single pseudonymous human operator and near-autonomous software agents.',
  '5. MMO Alternate Reality Game',
  'HyperMyths should be understood as an experimental MMO alternate reality game layered on token communities, AI media, internet markets, research quests, synthetic data generation quests and faction gameplay.',
  '6. Official Public Surfaces',
  'The intended public surfaces are https://hypermyths.com, https://polymyths.com, https://hypertian.com, https://cancerhawk.org, https://hyperkaon.com, https://asimog.com and https://tianezha.com. After this point, this disclosure refers to them by name only.',
  '7. Main World Layers',
  'HyperMyths is the AI media and myth engine. Polymyths is the game-world, server and governance layer. HyperTian is the advertising, attention and creator-market layer. CancerHawk is the cancer synthetic data generation quest layer. HyperKaon is the physics synthetic data generation quest layer. Asimog is the autonomous-agent log. Tianezha is the computation-market layer.',
  '8. Experimental Participation',
  'Participation is voluntary. Users should participate only because they want to test, play, build, create, research, generate synthetic data or experiment.',
  '9. Total Loss Risk',
  'The tokens may become worthless. The software may fail. The game may fail. The research quests may fail. The markets may behave irrationally.',
  '10. Token Communities as Factions',
  'Token communities can become playable factions instead of passive chart watchers.',
  '11. Two Faction Tokens',
  '$pMYTH is intended for the Solana/Pump faction. $bMYTH is intended for the Base/Clanker faction.',
  '12. Different Tokens, Different Worlds',
  '$pMYTH and $bMYTH are not identical. They may have different chains, communities, liquidity, mechanics, culture, fees and gameplay roles.',
  '13. No Equal Treatment Promise',
  'No one should assume both tokens will have the same price, market cap, liquidity, rewards, utility or attention.',
  '14. $pMYTH',
  '$pMYTH is intended to launch through Pump on Solana and represent the Solana-side faction inside the HyperMyths game world.',
  '15. $pMYTH Fees',
  'Any creator fees actually received from $pMYTH are project-side resources. Holders do not own those fees.',
  '16. $bMYTH',
  '$bMYTH is intended to launch through Clanker on Base chain and represent the Base-side faction inside the HyperMyths game world.',
  '17. $bMYTH Platform Mechanics',
  'Clanker, Base, bonding curves, liquidity migration, gas fees, approvals and trading mechanics are third-party or chain-specific systems. Holders do not own platform fees or liquidity.',
  '18. Token Utility',
  'The tokens may be used for faction identity, game access, daily tasks, weekly seasons, voting rituals, media generation, quests, research participation, synthetic data generation quests and reputation.',
  '19. No Guaranteed Utility',
  'Any utility may be delayed, changed, restricted, paused, replaced or never launched.',
  '20. Polymyths Governance Layer',
  'Polymyths is the governance layer for game-world proposals, faction coordination, voting rituals, reputation rules, quests, seasons, community signals and product direction signals.',
  '21. Governance Is Limited',
  'Token governance does not control legal entities, private wallets, hiring, investments, grants, patents, business deals, bank accounts, taxes, lawsuits, medical claims, scientific claims or confidential strategy.',
  '22. No Corporate Voting Rights',
  'Token votes are not shareholder votes, board votes, member votes, partnership votes, medical approvals, scientific approvals or legal directives.',
  '23. Token-Transfer Voting',
  'Some votes may work by sending $pMYTH or $bMYTH to posted voting addresses. Tokens sent to voting addresses may not be returned unless the proposal says so.',
  '24. Reputation',
  'Reputation may be earned through gameplay, tasks, testing, media, predictions, bug reports, community support, research work, synthetic data generation quests and governance participation.',
  '25. Reputation Is Not Money',
  'Reputation is an internal game mechanic. It is not equity, income, property, debt, scientific authority, medical authority or a guaranteed asset.',
  '26. Daily Tasks',
  'Daily tasks may include gameplay, model testing, agent testing, research review, synthetic data generation, bug reports, media creation, predictions, voting and faction coordination.',
  '27. Weekly Seasons',
  'Weekly seasons may score faction activity, quests, reputation, predictions, media, ads, research participation, synthetic data generation participation and gameplay.',
  '28. No Timeline Promise',
  'Daily tasks may not happen daily. Weekly seasons may not happen weekly. Roadmaps are not promises.',
  '29. MMO PvP and Co-op Logic',
  'The factions may compete on the surface, but the intended design is to recycle activity back into the broader ecosystem rather than permanently destroy losing factions.',
  '30. CancerHawk',
  'CancerHawk may support cancer research simulations, oncology-themed quests, synthetic cancer data generation, literature exploration, agent review and research-block workflows.',
  '31. CancerHawk Limits',
  'CancerHawk is not medical advice, clinical evidence, diagnosis, treatment, prevention, screening, a healthcare service or a substitute for doctors or researchers.',
  '32. HyperKaon',
  'HyperKaon may support physics research simulations, physics-themed quests, synthetic physics data generation, model testing, simulation review and research-block workflows.',
  '33. HyperKaon Limits',
  'HyperKaon is not scientific proof, peer review, lab validation, engineering certification, safety approval or a substitute for qualified physicists, engineers, institutions or formal research review.',
  '34. Asimog',
  'Asimog is intended as an autonomous-agent log and stream surface. It is not the governance layer and is not currently promised to be fully functional.',
  '35. Tianezha',
  'Tianezha is intended as the computation-market layer. It may support compute pricing, simulation markets, inference routing, validation, model testing and agent work. It is not currently promised to be fully functional.',
  '36. Computation Is Not Truth',
  'Computation-market outputs may be wrong. They are not truth, financial advice, legal advice, medical advice, scientific proof or guaranteed alpha.',
  '37. Prediction Markets',
  'Prediction markets may be used for game outcomes, research claims, faction seasons, agent performance, product milestones, computation outcomes and world events.',
  '38. Autonomous Agents',
  'The project may use autonomous, near-autonomous or semi-autonomous agents to test software, generate media, run research tasks, operate systems and experiment with markets.',
  '39. Agent Risk',
  'Agents may make mistakes, lose money, hallucinate, misread data, execute bad actions, generate bad research outputs, suffer exploits or be shut down.',
  '40. No Profit Rights',
  '$pMYTH and $bMYTH are not equity, debt, dividends, revenue rights, yield products, profit shares, treasury claims, patent claims, RWA claims, research ownership claims or agent-profit claims.',
  '41. User Responsibility',
  'Users are responsible for verifying official links, mint addresses, contract addresses, vote addresses, wallets, taxes, legal eligibility, medical interpretation, scientific interpretation and risk decisions.',
  '42. Final Acceptance',
  'By participating, the user accepts that HyperMyths is an experimental MMO alternate reality game, not a mature company, regulated financial platform, medical platform, scientific institution, investment product or guaranteed system. Participate only if you understand the risks and want to play, test, build, research, generate synthetic data and experiment.',
  'FULL DISCLOSURE STATEMENT',
  'THIS IS NOT INVESTMENT, TRADING, TAX, ACCOUNTING, FINANCIAL, MEDICAL, SCIENTIFIC, RESEARCH OR LEGAL ADVICE',
  '1. Purpose of This Disclosure',
  'This disclosure is published before the launch of $pMYTH and $bMYTH to explain the intended structure, purpose, risks, limits, mechanics, governance scope and experimental nature of the HyperMyths ecosystem.',
  'This disclosure is not investment advice, tax advice, trading advice, financial advice, accounting advice, medical advice, scientific advice, research advice or individualized legal advice to any purchaser, holder, staker, trader, contributor, developer, researcher, tester, creator, player, faction member or community participant.',
  'HyperMyths should be understood as an experimental MMO alternate reality game layered across token communities, AI media generation, internet capital markets, synthetic data generation quests, prediction markets, computation markets, autonomous agents, advertising systems, creator attention markets, governance experiments, research simulations and world-building.',
  'There is currently no corporation, company, foundation, association, DAO legal wrapper, formal legal entity, registered issuer, fund, clinic, hospital, laboratory, research institution, medical organization or scientific institution behind HyperMyths, $pMYTH or $bMYTH unless a separate public announcement says otherwise.',
  'There is only a single pseudonymous human operator and near-autonomous agents experimenting with software, agents, media, games, token communities, public internet markets, synthetic data generation, research quests, computation markets and world-building.',
  'No person should assume that there is a company treasury, board, management team, employee base, formal issuer, registered entity, audited balance sheet, corporate governance structure, clinical sponsor, scientific institution or legal organization behind the project.',
  'Any person who participates does so voluntarily and at their own risk. The tokens may be volatile, illiquid, manipulated, technically defective, economically unsuccessful, legally restricted or worthless. The software may fail. The agents may fail. The games may fail. The launchpads may change rules. The markets may behave irrationally. The research simulations may be wrong. The synthetic data may be useless. The project may change.',
  'Participation should be based only on a willingness to use, test, build, play, research, generate synthetic data, experiment and accept the possibility of total loss.',
  'This is an experiment. If everything was already known, stable, safe, clear and guaranteed, it would not be research, and it would not be a game.',
  '2. Project Overview',
  'HyperMyths is an experimental ecosystem for gamified internet capital markets, MMO alternate reality gameplay, AI media generation, token-community gaming, advertising, creator attention markets, prediction markets, computation markets, autonomous agents, open-source software testing, model testing, research coordination, governance experimentation, capital-management experiments, talent-management experiments, cancer synthetic data generation quests, physics synthetic data generation quests and community world creation.',
  'The basic idea is that token communities can become playable factions rather than passive groups of spectators watching a chart.',
  'A token community may generate media, create lore, buy ads, test models, run prediction markets, price computation, participate in faction governance, launch a game world, test open-source software, train or evaluate agents, route attention, coordinate creators, test capital allocation, test talent coordination, generate synthetic datasets, complete daily tasks and compete in weekly seasons.',
  'HyperMyths is intended to make community attention productive. Attention can become media. Media can become ads. Ads can become distribution. Distribution can become game activity. Game activity can become prediction markets. Prediction markets can become information. Information can become research. Research can become synthetic data generation. Synthetic data can become model testing. Model testing can become software improvement. Software improvement can become more worlds. More worlds can create more faction activity.',
  'Faction activity may create demand for computation, creative labor, agent operations, capital management, prediction, research review, data generation, simulation and attention routing.',
  'This is the experiment.',
  'The project is not presented as a stable product, mature financial system, regulated fund, investment company, broker, exchange, casino, bank, asset manager, talent agency, registered investment adviser, commodity trading adviser, medical provider, scientific institution, clinical trial sponsor or guaranteed income system.',
  'It is experimental beta software and experimental community infrastructure framed as an MMO alternate reality game.',
  '3. Preliminary Risk Statement',
  'Participation is highly risky.',
  'No person should buy, hold, stake, vote with, transfer, bridge, trade or use $pMYTH or $bMYTH with funds they cannot afford to lose.',
  'The tokens may go to zero. The websites may break. The servers may fail. The game may fail. The agents may hallucinate. The markets may be manipulated. The launchpads may change their rules. Smart contracts may fail. Prediction markets may resolve incorrectly. Computation markets may misprice work. Synthetic data generation quests may produce bad data. AI systems may generate inaccurate or misleading content. Advertising may fail. Community attention may disappear.',
  'No person should confuse a game mechanic with financial safety.',
  'No person should confuse token governance with corporate governance.',
  'No person should confuse synthetic data generation with real medical evidence or real scientific evidence.',
  'No person should confuse research simulations with clinical proof, peer review, laboratory validation or investment alpha.',
  'No person should confuse token ownership with ownership of software, agents, patents, treasury, websites, research, models, data, synthetic datasets or future business value.',
  'HyperMyths may be fun, useful, chaotic, educational, entertaining or productive. It may also fail completely.',
  '4. No Corporation, Entity or Formal Issuer',
  'There is currently no corporation, foundation, partnership, association, DAO legal wrapper, trust, medical organization, research entity, investment fund or other legal entity issuing, managing or guaranteeing $pMYTH, $bMYTH or HyperMyths unless a separate public announcement says otherwise.',
  'The project is operated by a single pseudonymous human operator and near-autonomous agents.',
  'References to the project, operator, ecosystem, treasury, agents, worlds, websites, markets, game layers, research layers, computation layers, synthetic data layers or future entities should not be understood as confirmation that a formal company or legal entity exists.',
  'If a legal entity, foundation, corporation, association, trust, DAO wrapper, operating company, holding company, research entity, nonprofit or other structure is formed in the future, that structure may have its own terms, disclosures, rights, duties, restrictions and limitations.',
  'The tokens do not automatically receive equity, membership interests, governance rights, voting rights, profit rights, information rights, liquidation rights, dividend rights, revenue rights, clinical rights, research ownership rights, synthetic dataset ownership rights or rights in any future structure.',
  'HyperMyths may, at its sole discretion, create future programs, conversions, grants, access systems, rewards or equity-related opportunities subject to terms and qualifications set later. No such program is guaranteed.',
  'No token holder should assume that there is a board, management team, registered issuer, corporate treasury, audited financial statement, employee base, investor-relations function, legal entity, research sponsor, medical sponsor, scientific sponsor or formal institution responsible for supporting the tokens.',
  '5. MMO Alternate Reality Game Framing',
  'HyperMyths is framed as an MMO alternate reality game.',
  'This means the ecosystem may combine real internet platforms, token launches, faction competition, AI media, game servers, lore, quests, prediction markets, computation markets, creator markets, public research simulations, synthetic data generation quests, advertising campaigns, autonomous agents and community governance into one persistent world.',
  'The game is not fully separate from the internet. It may use live markets, public social media, on-chain activity, token transfers, community servers, AI-generated content, public websites, creator campaigns, research simulations, synthetic datasets and faction coordination.',
  'A user may be a holder, player, tester, creator, researcher, meme maker, bug reporter, strategist, predictor, advertiser, quest runner, synthetic data generator, faction member or spectator.',
  'The MMO alternate reality game frame does not remove legal, technical, financial, medical, scientific, tax or personal risk. It is simply the intended design frame for understanding the ecosystem.',
  'The game may be chaotic. The game may be unfair. The game may be manipulated. The game may change. The game may fail.',
  '6. Public Surfaces and World Layers',
  'The official public surfaces are listed in Point 6 of the short 42-point summary above. After that listing, this disclosure refers to those surfaces by name only.',
  'HyperMyths is intended to operate as the AI media and myth engine. Its purpose is to let token communities, factions, creators, agents and users generate videos, trailers, lore, faction propaganda, token media, world assets, game content and AI-assisted creative outputs.',
  'Polymyths is intended to operate as the game-world, server, governance and faction coordination layer. Its purpose is to support playable token worlds, faction identity, daily tasks, weekly seasons, PvE and PvP events, quests, token-world experiments, voting rituals, reputation systems, community proposals and ecosystem governance signals.',
  'HyperTian is intended to operate as the advertising, attention and creator-market layer. Its purpose is to support advertising experiments, livestream-related promotion, creator attention, faction attention campaigns, community distribution, attention routing and creator-market mechanics.',
  'CancerHawk is intended to operate as the cancer synthetic data generation quest layer. Its purpose may include oncology-themed research simulations, public research blocks, AI-assisted literature exploration, synthetic cancer dataset generation, agent-reviewed research tasks, research interpretation experiments and community research quests.',
  'HyperKaon is intended to operate as the physics synthetic data generation quest layer. Its purpose may include physics-themed research simulations, synthetic physics dataset generation, model testing, simulation design, theory exploration, physics benchmark generation, agent-reviewed physics tasks and community research quests.',
  'Asimog is intended to operate as the autonomous-agent log, stream and observability layer. It is not the governance layer. It may show agent activity, agent status, logs, streams, experiments and operational traces. Asimog is not currently functional and should not be relied on as an available product.',
  'Tianezha is intended to operate as the computation-market layer. It may support compute pricing, inference routing, simulation markets, validation markets, model-testing markets, agent-work markets and synthetic data generation job markets. Tianezha is not currently functional and should not be relied on as an available product.',
  'No particular website is guaranteed to launch, remain online, remain unchanged, remain maintained, remain secure, remain useful, remain accurate or remain available.',
  'No token holder owns any of these websites.',
  'No token holder has a right to control the websites, force maintenance, force feature delivery, force open-sourcing, force research publication, force clinical review, force physics review, force computation-market activation or claim revenue from any website.',
  '7. The Two Tokens',
  'The first two HyperMyths faction tokens are $pMYTH and $bMYTH.',
  '$pMYTH is intended to launch through Pump on Solana and represent the Solana-side Pump faction inside the HyperMyths ecosystem.',
  '$bMYTH is intended to launch through Clanker on Base chain and represent the Base-side Clanker faction inside the HyperMyths ecosystem.',
  'The tokens are not intended to be identical instruments. They are intended to represent two separate factions using different chains, different launch environments, different mechanics, different communities and different gameplay identities.',
  'Their prices, liquidity, trading activity, holder distribution, fee mechanics, bonding-curve mechanics, governance influence, cultural identity and market behavior may differ substantially.',
  'The purpose of launching two tokens is to create native cross-chain faction rivalry. $pMYTH and $bMYTH may compete in daily tasks, weekly seasons, token-transfer voting, prediction markets, computation markets, media generation, ad campaigns, game worlds, model testing, agent-harness testing, open-source software testing, attention-routing experiments, talent-market experiments, synthetic data generation quests, research quests, community world launches and other ecosystem activity.',
  'No person should assume that $pMYTH and $bMYTH will trade at the same price, maintain equal liquidity, maintain equal market capitalization, receive equal attention, receive equal rewards or have identical rights or mechanics.',
  '8. $pMYTH Through Pump on Solana',
  '$pMYTH is intended to launch through Pump on Solana.',
  'Any creator fees actually received in connection with $pMYTH are intended to be project-side resources.',
  'They may be used for operations, servers, development, APIs, model inference, game systems, faction rewards, advertising, creator grants, community grants, agent operations, computation-market experiments, attention-market experiments, research simulations, synthetic data generation quests, RWA reward chests, treasury reserves, security, audits or other ecosystem purposes.',
  '$pMYTH holders do not own creator fees.',
  'Creator fees are not dividends. Creator fees are not interest. Creator fees are not passive income. Creator fees are not pro rata holder distributions. Creator fees are not guaranteed buybacks. Creator fees are not guaranteed burns. Creator fees are not guaranteed rewards. Creator fees are not guaranteed market-price support.',
  'The project may disclose creator-fee use, treasury use or reward use when appropriate, but no $pMYTH holder receives an automatic legal claim to any creator-fee revenue merely by buying, holding, trading, voting with, staking, transferring or using $pMYTH.',
  'Solana participation may involve wallet risk, token approval risk, fake contract risk, fake token risk, fake website risk, DEX routing risk, liquidity risk, MEV risk, platform risk, network risk and total-loss risk.',
  '9. $bMYTH Through Clanker on Base Chain',
  '$bMYTH is intended to launch through Clanker on Base chain.',
  'Clanker and Base chain mechanics may include bonding-curve trading, Base chain transaction fees, wallet approvals, platform-specific fees, migration to secondary markets if launchpad conditions are met and other chain-specific or platform-specific mechanics.',
  'The details may depend on Clanker rules, Base chain rules, wallet software, DEX routing, liquidity conditions, smart contracts and other third-party systems.',
  '$bMYTH holders do not own Clanker fees, Base chain fees, launchpad liquidity, treasury assets or platform revenues merely by holding $bMYTH.',
  'Platform mechanics are not dividends. Platform mechanics are not interest. Platform mechanics are not passive income. Platform mechanics are not pro rata holder distributions. Platform mechanics are not guaranteed buybacks. Platform mechanics are not guaranteed burns. Platform mechanics are not guaranteed rewards. Platform mechanics are not guaranteed market-price support.',
  'Users should understand that Base chain and Clanker participation may involve EVM wallet risk, token approval risk, contract risk, gas risk, liquidity risk, fake-site risk, bonding-curve risk, DEX migration risk, secondary-market trading risk and total-loss risk.',
  '10. Intended Utility',
  '$pMYTH and $bMYTH are intended to be used for faction participation and ecosystem activity.',
  'The intended uses may include faction identity, game access, daily tasks, weekly season participation, PvE and PvP gameplay, AI media generation, token trailers, faction videos, advertising participation, livestream advertising experiments, prediction-market participation, computation-market participation, token-transfer voting, reputation-weighted governance, model testing, agent-harness testing, open-source software testing, bug reporting, attention routing, creator marketplace participation, talent marketplace experiments, community world launches, lore creation, faction quests, cancer synthetic data generation quests, physics synthetic data generation quests, reward eligibility and other ecosystem activities.',
  'The tokens are intended to be used for participation and consumption inside a developing ecosystem.',
  'They are not intended to be passive investment contracts or claims on project income.',
  'No specific utility is guaranteed. Any utility may be delayed, modified, restricted, suspended, abandoned, replaced or never launched.',
  'The project may change based on technical limits, legal review, community behavior, market conditions, platform restrictions, security risks, infrastructure costs, medical-safety concerns, scientific-quality concerns, research-integrity concerns or operator judgment.',
  '11. Polymyths as the Governance Layer',
  'Polymyths is the intended governance layer for the HyperMyths ecosystem.',
  'Polymyths may coordinate game-world proposals, faction governance, token-transfer voting, reputation systems, world rules, quests, daily tasks, weekly seasons, PvE and PvP mechanics, community proposals, product signaling, ecosystem gameplay, reward themes, faction identity, server-level coordination, research-quest themes, synthetic data generation priorities and computation-market signals.',
  'Polymyths governance is intended to be game-world governance.',
  'It is not corporate governance. It is not legal-entity governance. It is not shareholder governance. It is not medical governance. It is not clinical governance. It is not scientific peer review. It is not investment-fund governance. It is not control over the operator’s private decisions, private wallets, confidential documents, legal strategy, investment applications, grants, contracts, employment, tax matters, patent filings, private infrastructure, clinical claims or scientific claims.',
  'Token-holder governance, if any, is limited to the game world, faction mechanics, community proposals, product signaling, reputation systems, voting rituals and ecosystem gameplay unless a separate written document expressly provides otherwise.',
  '12. Token-Transfer Voting',
  'The project may use token-transfer voting.',
  'A proposal may publish one or more voting addresses. Sending $pMYTH or $bMYTH to a designated address may count as a vote.',
  'For one proposal, $pMYTH may represent one voting choice and $bMYTH may represent another voting choice. For another proposal, the mapping may alternate. Each proposal should clearly state the rules before voting begins.',
  'Because $pMYTH and $bMYTH are intended to exist on different chains, token-transfer voting may require different voting addresses, different wallet interactions, different transaction steps, different confirmation times and different chain-specific risk disclosures.',
  'Tokens sent to vote addresses may not be returned unless the proposal expressly says otherwise. They may be burned, retained, routed to treasury, redistributed, counted only for signaling, used in game mechanics or treated in another disclosed manner.',
  'Voting may be weighted by token amount, earned faction reputation, anti-whale dampening, participation history, chain-specific participation, synthetic data generation participation, research participation, quest completion or other disclosed factors.',
  'Token-transfer voting is a community, game, faction and product-governance mechanism.',
  'It is not corporate shareholder voting. It does not provide equity, board rights, statutory voting rights, profit rights, fiduciary rights or ownership of any legal entity.',
  '13. Limited Scope of Token-Holder Governance',
  'Any token-holder governance associated with $pMYTH or $bMYTH is limited to the game world and ecosystem participation mechanics unless a separate written document expressly provides otherwise.',
  'Token-holder governance may relate to faction lore, quests, game-world proposals, reputation rules, community priorities, non-binding product signals, reward themes, season mechanics, daily tasks, token-transfer voting rituals, synthetic data quest themes, computation-market themes or other internal ecosystem matters.',
  'Token-holder governance does not govern legal entities, real-world company decisions, securities offerings, investment applications, grants, accelerator applications, venture financings, loans, partnerships, employment, IP ownership, patent prosecution, litigation, tax matters, custody arrangements, treasury custody, bank accounts, private wallets, confidential documents, software licensing, open-source timing, platform contracts, regulatory strategy, medical claims, clinical claims, healthcare advice, scientific claims, synthetic data validity or research validity.',
  'No token-holder vote should be understood as a shareholder vote, board vote, member vote, partnership vote, fiduciary instruction, legal directive, medical directive, research approval, peer review or enforceable corporate action.',
  'Token votes are game-world and community-governance signals unless expressly stated otherwise.',
  '14. Reputation',
  'The project may use reputation systems.',
  'Reputation may be earned through gameplay, daily tasks, media generation, ad participation, model testing, agent-harness testing, open-source software testing, bug reports, prediction accuracy, community support, world creation, faction quests, governance participation, computation-market participation, attention-market participation, creator contribution, cancer synthetic data generation quests, physics synthetic data generation quests, Solana-side participation, Base-side participation or other useful activity.',
  'Reputation may affect voting weight, reward eligibility, quest access, faction status, leaderboard position, agent permissions, media priority, computation priority, creator-market access, synthetic data generation access, research quest access or other ecosystem mechanics.',
  'Reputation may be reduced, removed, limited, reset or ignored for cheating, Sybil attacks, spam, bot abuse, wash activity, market manipulation, harassment, malicious reporting, exploit use, impersonation, fake engagement, research spam, medical misinformation, scientific misinformation, synthetic data spam or other harmful conduct.',
  'Reputation is an internal ecosystem mechanic.',
  'It is not equity, money, property, debt, income, medical credential, scientific credential, research credential or a guaranteed asset.',
  '15. Daily Tasks',
  'HyperMyths may include daily tasks, recurring quests, one-time events, faction challenges, model-testing missions, agent-testing missions, software-testing tasks, prediction tasks, gameplay tasks, media tasks, ad tasks, research tasks, synthetic data generation tasks, bug-reporting tasks, voting tasks and community coordination tasks.',
  'Daily tasks may be used to create frequent participation. They may affect faction reputation, player status, task streaks, access, quest visibility, reward eligibility, season scoring, research participation, synthetic data generation access or game-world progression.',
  'Daily tasks may include generating AI media, testing prompts, reviewing outputs, submitting bug reports, running research simulations, generating synthetic cancer datasets, generating synthetic physics datasets, comparing model results, making predictions, joining PvP events, joining PvE events, supporting faction strategy, testing open-source tools or helping community coordination.',
  'Daily tasks are not guaranteed.',
  'A task may not appear every day. A task may be delayed, cancelled, changed, reset, paused, ignored, restricted or removed.',
  'No task, streak, leaderboard, quest, milestone, roadmap or daily schedule should be understood as a promise.',
  '16. Weekly Seasons',
  'HyperMyths may run weekly or recurring faction seasons.',
  'Weekly seasons may aggregate daily activity, price-independent participation, faction performance, prediction accuracy, AI media generation, ad activity, computation-market activity, research participation, synthetic data generation participation, model testing, game activity, open-source testing and community contributions into broader faction outcomes.',
  'Season scoring may include daily task participation, price performance, liquidity depth, holder growth, volume quality, game activity, AI media generation, ad participation, prediction-market activity, prediction accuracy, model-testing activity, agent-testing activity, open-source software testing, research quest participation, synthetic data generation quality, bug reports, world launches, lore objectives, computation-market activity, attention-market activity, creator contribution, Solana-side activity and Base-side activity.',
  'Winners may receive season points, cosmetics, lore advantages, world influence, territory, leaderboard placement, media priority, reputation boosts or other gameplay/status benefits.',
  'Losers may receive comeback quests, underdog multipliers, revenge arcs, recovery missions or other participation opportunities.',
  'Weekly seasons are not guaranteed.',
  'A season may be delayed, extended, shortened, cancelled, modified, repeated, ignored or replaced. Rewards connected to tasks or seasons may be changed, delayed, restricted, substituted or cancelled.',
  '17. PvP on the Surface and Cooperative Accounting Underneath',
  'The project may run competitive faction seasons between $pMYTH, $bMYTH and future faction tokens or worlds.',
  'The project is not intended to permanently cannibalize one faction for the benefit of another.',
  'Losing factions are not intended to be erased or structurally treated as exit liquidity. If seasonal flows, fees, penalties, vote transfers or other assets go to treasury, the intended use is to recycle value into ecosystem activity, game rewards, comeback quests, grants, ad credits, RWA chests, infrastructure, agent operations, research quests, synthetic data generation quests or future development.',
  'The intended principle is PvP on the surface and cooperative ecosystem accounting underneath.',
  'A faction can lose a battle without being removed from the world.',
  'A faction can win a season without receiving any guaranteed financial benefit.',
  'A faction can dominate attention while still suffering token volatility.',
  'This is a game-world design principle, not a financial promise.',
  '18. CancerHawk Synthetic Data Generation Quest Layer',
  'CancerHawk is intended to operate as the cancer synthetic data generation quest layer inside the broader HyperMyths MMO alternate reality game.',
  'CancerHawk may allow users, factions, agents and communities to explore oncology-related research questions, generate synthetic cancer datasets, run simulations, compare literature, test AI reasoning, create structured research blocks, produce hypotheses, evaluate claims and participate in themed research workflows.',
  'CancerHawk may involve cancer-related concepts, oncology literature, treatment-related hypotheses, biological mechanisms, simulated patient-like data, simulated lab data, simulated trial-like structures, synthetic biomedical datasets and research-block generation.',
  'CancerHawk synthetic data generation quests may be used for model testing, AI evaluation, research exploration, educational simulations, prediction-market questions, computation-market jobs, benchmark construction and faction gameplay.',
  'All outputs should be treated as experimental.',
  'Synthetic cancer data is not real clinical data unless clearly stated.',
  'Synthetic cancer data is not medical evidence.',
  'Synthetic cancer data is not proof that a therapy works.',
  'Synthetic cancer data is not proof that a biological mechanism is true.',
  'Synthetic cancer data is not a substitute for real studies, real trials, real patient data, expert review or clinical validation.',
  'CancerHawk may be useful as a game-world research quest surface, but the existence of quests, points, reputation, faction participation, AI summaries, agent reviews or generated datasets does not make the output clinically valid.',
  '19. CancerHawk Medical Limits',
  'CancerHawk is not a medical provider.',
  'CancerHawk is not a hospital. CancerHawk is not a clinic. CancerHawk is not a doctor. CancerHawk is not a clinical trial sponsor. CancerHawk is not a substitute for professional medical advice, diagnosis, treatment, screening, prevention or care.',
  'Any research block, model output, AI interpretation, simulation, hypothesis, ranking, explanation, summary, generated report, literature comparison, synthetic cancer dataset or agent review connected to CancerHawk should be treated as experimental software output.',
  'It may be incomplete, speculative, wrong, outdated, hallucinated, misleading, overconfident or unsuitable for real-world decisions.',
  'No person should use CancerHawk or any HyperMyths-related research output to diagnose, treat, cure, prevent or manage cancer or any other disease.',
  'Patients, caregivers, researchers and readers should consult qualified medical professionals and appropriate scientific sources before making health-related decisions.',
  'No person should interpret CancerHawk participation as entering a doctor-patient relationship, clinical trial, medical study, hospital program, research institution, healthcare product or regulated medical service.',
  '20. HyperKaon Synthetic Data Generation Quest Layer',
  'HyperKaon is intended to operate as the physics synthetic data generation quest layer inside the broader HyperMyths MMO alternate reality game.',
  'HyperKaon may allow users, factions, agents and communities to explore physics-related research questions, generate synthetic physics datasets, run simulations, compare theories, test AI reasoning, create structured research blocks, produce hypotheses, evaluate claims and participate in themed research workflows.',
  'HyperKaon may involve physics concepts, mathematical simulations, particle physics themes, quantum systems, field theory themes, cosmology, synthetic measurement data, simulated experimental data, benchmark problems, model-generated physics datasets and research-block generation.',
  'HyperKaon synthetic data generation quests may be used for model testing, AI evaluation, research exploration, educational simulations, prediction-market questions, computation-market jobs, benchmark construction and faction gameplay.',
  'All outputs should be treated as experimental.',
  'Synthetic physics data is not real experimental data unless clearly stated.',
  'Synthetic physics data is not scientific proof.',
  'Synthetic physics data is not peer review.',
  'Synthetic physics data is not lab validation.',
  'Synthetic physics data is not proof that a theory is true.',
  'Synthetic physics data is not proof that an engineering design is safe.',
  'HyperKaon may be useful as a game-world research quest surface, but the existence of quests, points, reputation, faction participation, AI summaries, agent reviews or generated datasets does not make the output scientifically valid.',
  '21. HyperKaon Scientific Limits',
  'HyperKaon is not a scientific institution.',
  'HyperKaon is not a university. HyperKaon is not a physics laboratory. HyperKaon is not a peer-review journal. HyperKaon is not an engineering certification body. HyperKaon is not a safety certification system.',
  'HyperKaon is not a substitute for qualified physicists, engineers, researchers, peer reviewers, laboratories, institutions or domain experts.',
  'Any model output, generated equation, physics explanation, simulation, synthetic dataset, benchmark, hypothesis, theory comparison, generated report, agent review or research block connected to HyperKaon should be treated as experimental software output.',
  'It may be incomplete, speculative, wrong, outdated, hallucinated, misleading, overconfident, mathematically invalid, physically impossible or unsuitable for real-world engineering or scientific decisions.',
  'No person should use HyperKaon or any HyperMyths-related physics output as proof of a theory, proof of an engineering design, proof of a safety claim, proof of a device or proof of a real-world experiment.',
  'No person should interpret HyperKaon participation as entering a formal research institution, scientific collaboration, peer-review process, engineering certification program or laboratory validation program.',
  '22. Synthetic Data Generation Quests',
  'The project may use synthetic data generation quests across cancer, physics, AI, game systems, prediction markets, computation markets and other domains.',
  'Synthetic data generation quests may involve creating artificial datasets, simulated examples, generated research cases, model-generated trials, simulated measurements, hypothetical experiments, benchmark tasks, adversarial examples, validation sets, training examples, evaluation prompts or structured research blocks.',
  'Cancer-related synthetic data generation quests may involve simulated oncology research structures, simulated biological relationships, simulated trial-like records, generated literature comparisons, generated treatment hypotheses, generated biomarker examples or generated research review tasks.',
  'Physics-related synthetic data generation quests may involve simulated measurements, generated equations, generated physical scenarios, synthetic particle data, synthetic quantum tasks, generated cosmology examples, generated benchmark problems, simulated instrument readings or theory-testing prompts.',
  'Synthetic data may be useful for testing software, testing AI models, building game quests, creating benchmarks, exploring hypotheses and training evaluation systems.',
  'Synthetic data may also be wrong, biased, unrealistic, unsafe, misleading, contaminated, overfit, hallucinated, mathematically invalid, medically invalid, scientifically invalid or legally sensitive.',
  'No person should rely on synthetic data generation quests for medical decisions, clinical decisions, scientific proof, engineering safety, financial decisions, legal decisions or investment decisions.',
  '23. Frontier AI Research Tokenization',
  'HyperMyths is also an experiment in Frontier AI Research tokenization.',
  'This phrase means token communities may become coordinated, reputation-weighted, incentive-aligned participation groups for testing frontier AI systems, agent harnesses, open-source tools, media generation systems, game systems, prediction systems, computation markets, capital-allocation workflows, attention markets, research workflows, research-simulation systems and synthetic data generation workflows.',
  'Frontier AI Research tokenization does not mean token holders own AI research.',
  'It does not mean token holders own model weights, datasets, prompts, software, agents, websites, patents, research outputs, trade secrets, attention systems, capital-management systems, talent systems, medical discoveries, scientific discoveries, synthetic datasets or future commercial upside.',
  'It does not mean token holders are investors in an AI lab.',
  'It does not mean token holders are employees, contractors, partners, shareholders, creditors, patients, clients, customers of a regulated advisory business or beneficiaries of a managed investment product.',
  'Factions may test new models, evaluate outputs, compare agent performance, submit bugs, test open-source tools, generate media, create benchmark tasks, run predictions, test governance mechanics, route attention, evaluate creator performance, evaluate talent-market mechanics, test capital-allocation ideas, participate in cancer synthetic data generation quests, participate in physics synthetic data generation quests and participate in community research workflows.',
  'These activities are experimental participation. They are not equity ownership, employment, partnership, fiduciary relationship, medical relationship, healthcare relationship, scientific credentialing, agency relationship or guaranteed compensation.',
  '24. Tianezha and Computation Markets',
  'Tianezha is intended as the computation-market layer.',
  'Tianezha is not currently functional and should not be treated as an available, reliable or launched product.',
  'HyperMyths may include computation markets enabled by Tianezha, x402, traditional inference providers, blockchain payments, off-chain systems or other infrastructure.',
  'A computation market is an experimental mechanism for pricing, routing, prioritizing, validating, replicating or allocating compute, inference, model testing, prediction work, simulation work, agent work, media generation, synthetic data generation, research tasks or other computational activity.',
  'The purpose of a computation market is not to magically price truth. The purpose is to price work, urgency, validation, replication, access, priority, exclusivity and resource allocation.',
  'A computation market may help determine which jobs are run, which model outputs are tested, which agent workflows receive resources, which faction receives priority, which predictions are validated, which simulations are repeated, which synthetic datasets are generated, which research tasks receive compute or which outputs become visible in a world.',
  'Computation markets may be wrong. They may misprice urgency. They may misallocate resources. They may reward spam. They may be attacked. They may produce inaccurate outputs. They may fail to validate results. They may overvalue useless work or undervalue important work. They may depend on third-party infrastructure, model providers, cloud providers, blockchain systems, data providers, APIs or agents that fail.',
  'No person should treat computation-market output as truth, investment advice, financial advice, scientific proof, medical advice, legal advice or guaranteed alpha.',
  'Computation markets are experimental coordination tools and may fail.',
  '25. Asimog and Autonomous-Agent Logs',
  'Asimog is intended as the autonomous-agent log, stream and observability layer.',
  'Asimog is not currently functional and should not be treated as an available, reliable or launched product.',
  'Asimog may show agent status, agent activity, agent streams, autonomous operation logs, task execution traces, supervisor outputs, system events, experimental agent behavior and other records of agent activity.',
  'Asimog logs should not be treated as audited records, financial statements, medical records, scientific validation, legal records, investor disclosures, complete transaction histories or guaranteed truth.',
  'The existence of an agent log does not create token-holder rights.',
  'The absence of a log does not create token-holder compensation rights.',
  'The project may choose what to log, what not to log, what to redact, what to delay, what to summarize and what to remove.',
  'Agent logs may be incomplete, delayed, inaccurate, manipulated, hallucinated, corrupted, lost or unavailable.',
  '26. Autonomous Agent Authority and Risk',
  'The project may deploy autonomous, near-autonomous or semi-autonomous agents.',
  'These agents may learn, adapt, monitor, test, trade, deploy, execute and operate across multiple systems.',
  'Agents may observe markets, trade spot tokens, trade perpetuals, trade derivatives where available, trade prediction-market positions, interact with DeFi protocols, route assets across chains, interact with bridges, execute cross-chain strategies, manage experimental treasury positions, rebalance assets, test arbitrage, trade RWAs where legally and technically available, deploy websites, generate media, test models, test agent harnesses, test open-source software, create reports, create prediction markets, support game operations, support attention-market experiments, support computation markets, support capital-management experiments, support research simulations, generate synthetic datasets and perform other authorized tasks.',
  'The agent may trade on any chain, protocol, venue or market that is legally and technically available to it, including spot markets, perpetuals, prediction markets, liquidity pools, lending protocols, RWA venues and cross-chain systems.',
  'The scope of agent activity may expand or contract over time.',
  'The agent may learn from data, previous outcomes, market behavior, faction behavior, treasury outcomes, prediction results, model tests, attention outcomes, computation outcomes, research simulations, synthetic data generation outcomes and user interactions.',
  'The agent may change strategies.',
  'The agent may make mistakes.',
  'The agent is not an investment adviser to token holders. The agent is not a broker for token holders. The agent is not a fund manager for token holders. The agent is not a commodity trading adviser for token holders. The agent is not a doctor. The agent is not a medical professional. The agent is not a clinical researcher. The agent is not a physicist. The agent is not a scientific peer reviewer.',
  'The agent is not managing individual user accounts or individual user health decisions.',
  'The agent is an experimental project tool and treasury/operator tool unless a separate program expressly says otherwise.',
  '27. Agent Profits, Agent Losses and No Holder Claims',
  'Agent profits, if any, do not automatically belong to $pMYTH or $bMYTH holders.',
  'Agent losses, if any, do not create compensation rights for holders.',
  'Agent activity may lose money, suffer liquidation, suffer bridge failure, suffer oracle failure, suffer smart contract exploits, suffer platform outages, suffer bad fills, suffer MEV, suffer slippage, misread data, hallucinate, execute bad trades, generate bad research, generate bad synthetic data, publish wrong outputs or be compromised.',
  'No person should participate in $pMYTH or $bMYTH based on an expectation that an agent will generate profit, support price, maintain a floor, produce yield, distribute trading gains to holders, produce valid research, produce valid synthetic data, create medical breakthroughs or create scientific breakthroughs.',
  'An agent may be useful inside the game. An agent may also be wrong, unstable, expensive, compromised or useless.',
  '28. Prediction Markets',
  'The project may use prediction markets through third-party venues or other systems.',
  'Prediction markets may be used for faction seasons, model benchmark outcomes, game outcomes, agent performance, product milestones, treasury milestones, world launches, ad campaigns, research predictions, community events, computation-market outcomes, capital-management outcomes, attention-market outcomes, cancer research questions, physics research questions, synthetic data generation outcomes or other ecosystem questions.',
  'Prediction markets are risky.',
  'They may involve leverage, liquidation, loss, incorrect resolution, disputed resolution, manipulation, low liquidity, oracle failure, smart contract failure, regulatory limits, jurisdictional restrictions, tax consequences and total loss of funds.',
  'Prediction markets are intended as game, research, coordination and information tools.',
  'They are not risk-free products.',
  'HyperMyths does not guarantee prediction-market profits, does not guarantee market resolution and does not guarantee that any user may lawfully access any prediction market in their jurisdiction.',
  'Prediction markets about medical, scientific, synthetic data or oncology-related topics should not be treated as medical truth, scientific truth, clinical proof, peer review or treatment guidance.',
  '29. Attention Economy, Creator Attention Marketplace and Ad Systems',
  'HyperMyths may include attention-economy mechanics and creator attention marketplace experiments.',
  'These may involve AI-generated media, token trailers, faction propaganda, livestream ads, ad credits, token-community promotion, creator campaigns, attention-routing tools, content marketplaces, influencer-style experiments, distribution experiments and creator-talent coordination.',
  'The goal is to test whether token communities can convert attention into useful media, testing, research, predictions, synthetic data generation, game activity and market participation.',
  'The project may allow factions, creators, token communities or agents to compete for attention, buy attention, route attention, generate attention, analyze attention or reward attention.',
  'No attention outcome is guaranteed. No creator campaign is guaranteed. No advertising performance is guaranteed. No conversion is guaranteed. No reach is guaranteed. No impressions, clicks, views, followers, volume, liquidity, users, revenue, research impact, synthetic data quality or token performance are guaranteed.',
  'The project is not responsible for platform moderation, social-media algorithm changes, creator misconduct, misleading third-party content, fake engagement, bot activity, influencer behavior, ad platform restrictions, livestream platform restrictions, medical misinformation posted by third parties, scientific misinformation posted by third parties or user losses caused by attention campaigns.',
  'Any creator marketplace or attention marketplace is experimental beta software and may be modified, restricted, discontinued or never launched.',
  '30. Capital Management Experiments',
  'HyperMyths may include capital-management experiments involving treasury assets, autonomous agents, cross-chain assets, spot tokens, perpetuals, prediction positions, RWAs, DeFi positions, liquidity pools, lending positions or other legally and technically accessible markets.',
  'These capital-management experiments are not offered as an investment product to token holders.',
  'Token holders do not deposit funds for management. Token holders do not receive pro rata ownership of managed assets. Token holders do not receive a right to agent trading profits. Token holders do not receive a right to treasury gains. Token holders do not receive fiduciary duties, advisory services, brokerage services, commodity trading advisory services, fund interests or managed account services.',
  'The project may use capital-management tools for treasury experimentation, agent learning, game rewards, ecosystem operations or research purposes.',
  'Such activity may lose money. It may suffer liquidation, bad fills, smart contract failures, platform failures, oracle failures, bridge failures, regulatory restrictions, tax consequences, custody failures and operational errors.',
  'No person should buy, hold, stake, vote with or use $pMYTH or $bMYTH based on an expectation that capital-management experiments will generate profit, support token price, fund rewards, maintain liquidity or create holder distributions.',
  '31. Talent Management and Launch Systems for Others',
  'HyperMyths may include talent-management experiments, creator coordination, contributor coordination, agent-assisted talent routing, token-community launch tooling and world-launch systems for other creators, developers, agents, teams, projects, researchers or token communities.',
  'These systems may help creators, builders, communities, agents or token projects launch worlds, generate media, test software, run predictions, create campaigns, coordinate tasks, participate in faction economies or run synthetic data generation quests.',
  'They may also be referenced in patent, provisional patent, invention or documentation materials.',
  'No person should interpret these systems as a promise that HyperMyths will act as a licensed talent agency, employment agency, broker, investment adviser, marketing agency, publisher, exchange, underwriter, guarantor, medical organization, research institution, clinical trial sponsor, scientific institution or fiduciary.',
  'Any talent-management or launch-management system is experimental beta software and may be incomplete, private, patent-related, restricted, abandoned or never launched.',
  'HyperMyths may choose not to provide additional information about patent-related talent-management systems, launch systems, attention marketplaces, capital-management systems, research systems, synthetic data systems or computation-market systems beyond what is publicly disclosed.',
  'Certain information may be confidential, proprietary, patent-sensitive, security-sensitive, medical-safety-sensitive, scientific-integrity-sensitive or trade-secret-protected.',
  'Token holders do not have a right to receive further information, private documentation, private claims, private architecture, source code, commercial plans, patent details, research details or internal strategy.',
  '32. RWA Rewards',
  'The project may use RWA reward chests sourced through third-party venues or other mechanisms.',
  'RWA reward chests may involve tokenized treasuries, tokenized ETFs, tokenized metals, tokenized stocks, stablecoins, tokenized cash-equivalents, credits or other disclosed assets.',
  'The exact asset may be hidden for game, lore or season purposes, but the general category, eligibility rules, restrictions and risks should be disclosed before the relevant reward program.',
  'RWA rewards are not guaranteed.',
  'They are not dividends. They are not interest. They are not yield. They are not pro rata distributions. They are not owed to token holders. They are not automatic.',
  'They may require eligibility review, KYC, jurisdictional restrictions, issuer approval, transfer limits, liquidity availability, custody arrangements, tax analysis, sanctions checks or other conditions.',
  'The project may substitute, delay, cancel or modify RWA rewards.',
  'A user may be ineligible to receive an RWA reward even if the user participated in the game or held tokens.',
  'No person should buy, hold, stake, vote with or use $pMYTH or $bMYTH based on an expectation of receiving RWA assets.',
  '33. Treasury',
  'The project may maintain one or more treasury wallets across one or more chains.',
  'Treasury sources may include creator fees, platform mechanics, product revenue, ads, AI media generation, game servers, prediction-related activity, computation-market activity, agent activity, attention-market activity, creator-market activity, token-transfer voting flows, grants, sponsorships, community payments, research-related payments, synthetic data generation payments or other ecosystem revenue.',
  'Treasury uses may include infrastructure, servers, APIs, model inference, storage, development, security, audits, game rewards, faction rewards, comeback quests, RWA reward chests, future expansion reserves, agent operations, open-source testing bounties, model-testing rewards, research quest rewards, synthetic data generation rewards, ad credits, grants, creator-market experiments, computation-market experiments, capital-management experiments, CancerHawk infrastructure, HyperKaon infrastructure, Tianezha infrastructure, Asimog infrastructure and general ecosystem development.',
  'Holding $pMYTH or $bMYTH does not grant ownership of the treasury.',
  'The treasury is not a dividend pool. The treasury is not a pro rata holder distribution account. The treasury is not a guaranteed reward source.',
  'The treasury is an ecosystem resource controlled according to disclosed project rules, operator judgment, platform constraints, legal review, technical constraints and any applicable Polymyths governance process.',
  '34. HYPE, Future Tokens and Future Expansion',
  'The project may reserve funds, attention, tooling, agent activity or community energy for future ecosystem expansion.',
  'This may include new faction tokens, new chain deployments, new game worlds, new research quest surfaces, new computation-market surfaces, new media products, new creator-market systems, new agent systems or future Hyperliquid-related or HYPE-related activity.',
  'No holder is guaranteed any future token.',
  'No holder is guaranteed a Hyperliquid launch, listing, token, allocation, airdrop, perpetuals market or HYPE-related benefit.',
  'Any future chain, future token, future launch or future expansion program would require separate disclosure and may never occur.',
  'No person should buy, hold, stake, vote with or use $pMYTH or $bMYTH based on an expectation of receiving HYPE, a future token, a future allocation or any future expansion benefit.',
  '35. Patent and Intellectual Property Disclosure',
  'The project may involve patents, provisional patent applications, patent-pending systems, invention disclosures, copyrighted works, trade secrets, trademarks, software, interfaces, agent systems, media systems, game systems, computation markets, attention marketplaces, creator marketplaces, capital-management systems, talent-management systems, launch systems for others, research workflows, cancer synthetic data workflows, physics synthetic data workflows and other intellectual property.',
  'Holding $pMYTH or $bMYTH does not grant any ownership, license, assignment, commercialization right, enforcement right, revenue right, research right, clinical right, scientific right, dataset right or control right with respect to any patent, patent application, invention, software, codebase, agent, model, dataset, synthetic dataset, documentation, website, trademark, media asset, market system, talent system, attention system, capital system, research system or research output.',
  'No token holder receives a right to use, copy, commercialize, sublicense, enforce, sell, transfer or claim ownership in any project intellectual property merely by holding or using a token.',
  'Any open-source software remains subject to its applicable license.',
  'Any private code, trade secret, unpublished patent material, confidential research, market architecture, capital-management architecture, attention-market architecture, medical-safety-sensitive workflow, scientific-integrity-sensitive workflow, synthetic data system or talent-management architecture remains controlled by its owner.',
  'The tokens are not intellectual-property ownership instruments.',
  '36. Patent-Related Confidentiality and Limited Disclosure',
  'Certain aspects of HyperMyths may be described or contemplated in patent, provisional patent, invention disclosure or related documentation.',
  'These may include computation markets, attention economy systems, creator attention marketplaces, capital-management systems, launch systems for other communities, talent-management systems, agent workflows, media systems, game systems, governance systems, research systems, cancer synthetic data generation systems, physics synthetic data generation systems and related workflows.',
  'The project may choose not to provide additional information about these systems beyond public disclosures.',
  'Patent-related materials may contain confidential, proprietary, technical, strategic, scientific, medical or legally sensitive information.',
  'Nothing in the launch of $pMYTH or $bMYTH creates any obligation to publish patent claims, specifications, diagrams, source code, private documentation, commercial strategy, trade secrets, research architecture, synthetic data architecture or implementation details.',
  'No token holder has a right to inspect, receive, rely upon or demand further information about patent materials, confidential systems, capital-management systems, attention marketplaces, talent-management systems, launch systems, research systems, synthetic data systems or computation-market systems.',
  '37. Open Source Disclosure',
  'The project may make some software, contracts, documentation, tools, prompts, interfaces, agents, tests, libraries or research artifacts open source at its discretion.',
  'Open-sourcing may occur for transparency, community testing, security review, adoption, composability, research participation or ecosystem growth.',
  'No person should assume that any specific component will be open sourced.',
  'The project may keep some components private for security, patent, trade secret, operational, anti-abuse, competitive, medical-safety, scientific-integrity, research-integrity or safety reasons.',
  'The project may also open source one component while keeping other related components private.',
  'Token holders do not receive a right to force open-source release.',
  'Token holders do not receive ownership of open-source software.',
  'Open-source components, if released, will be governed by their applicable license terms.',
  'Private components remain private unless and until the project chooses otherwise.',
  '38. Off-Chain Applications, Grants, Investments and Reserved Decisions',
  'The project, operator, related persons, affiliated persons, successor entities, future entities or agents may apply for, negotiate, accept, reject or abandon investments, grants, accelerator programs, hackathons, venture funding, loans, sponsorships, commercial contracts, strategic partnerships, exchange relationships, cloud credits, ecosystem funding, research funding, creator partnerships, talent relationships, publishing relationships, licensing arrangements, IP transactions, acquisition opportunities, joint ventures or other opportunities.',
  'These off-chain applications and relationships are not governed by $pMYTH or $bMYTH holders.',
  'Token holders do not have a right to approve, reject, veto, inspect, control, direct or participate in investment applications, grant applications, accelerator applications, venture financing, loans, sponsorships, contracts, partnership terms, cap tables, investor communications, IP strategy, patent strategy, hiring, firing, commercial negotiations, private treasury custody, source code access, private documents or confidential business strategy.',
  'Token-holder governance, if any, is limited to the game world, faction mechanics, community proposals, product signaling, reputation systems, voting rituals and ecosystem gameplay.',
  'Token-holder governance does not extend to real-world corporate governance, legal-entity governance, investment decisions, securities offerings, financing transactions, employment matters, IP ownership, patent prosecution, litigation, tax matters, custody arrangements, treasury custody, bank accounts, private wallets, confidential documents, software licensing, open-source timing, platform contracts, medical claims, scientific claims or regulatory strategy.',
  'The project may choose to disclose certain off-chain developments voluntarily, but no token holder has a general right to receive confidential information, private records, financial statements, investment documents, correspondence, investor decks, legal opinions, patent filings, bank records, source code, cap tables, payroll records, tax records or internal strategy documents, except where required by applicable law.',
  '39. No Affiliation With Third Parties',
  'HyperMyths, $pMYTH and $bMYTH are independent.',
  'They are not affiliated with, endorsed by, approved by, sponsored by, audited by, guaranteed by or officially partnered with Solana, Solana Foundation, Pump, Base chain, Clanker, X, any accelerator, any hackathon, any RWA issuer, any prediction-market platform, any model provider, any cloud provider, any open-source project, any cancer organization, any hospital, any university, any physics laboratory, any scientific institution, any medical institution, any government agency or any other third party unless there is a separate written announcement by both sides.',
  'Using a platform does not create affiliation.',
  'Launching through Pump does not mean Pump endorses $pMYTH.',
  'Launching through Clanker does not mean Clanker endorses $bMYTH.',
  'Building on Solana does not mean Solana endorses the project.',
  'Building on Base chain does not mean Base chain endorses the project.',
  'Posting on X does not mean X endorses the project.',
  'Using a cancer research theme does not mean any medical institution endorses the project.',
  'Using a physics research theme does not mean any scientific institution endorses the project.',
  'Using AI research workflows does not mean any AI lab endorses the project.',
  'Participating in a hackathon, accelerator, builder program, grant program or ecosystem program does not mean approval, endorsement, investment, sponsorship, affiliation, review, audit, partnership, guarantee, certification, medical validation, scientific validation or legal approval by any third party.',
  '40. No Investment Rights and No Guaranteed Rewards',
  '$pMYTH and $bMYTH do not grant equity, stock, debt, bonds, notes, dividends, interest, revenue rights, profit-sharing rights, liquidation rights, redemption rights, company voting rights, board rights, fiduciary rights, ownership of treasury, ownership of patents, ownership of agents, ownership of models, ownership of software, ownership of websites, ownership of RWAs, ownership of future expansion reserves, ownership of future research, ownership of future products, ownership of computation markets, ownership of attention markets, ownership of capital-management systems, ownership of talent-management systems, ownership of CancerHawk, ownership of HyperKaon, ownership of Asimog, ownership of Tianezha or ownership of any research output.',
  'The tokens are experimental faction-participation tokens.',
  'They are intended for use, experimentation, gameplay, governance signaling, media, advertising, model testing, agent testing, open-source testing, prediction participation, computation-market participation, attention-market participation, research simulation, synthetic data generation and community world creation.',
  'They are not intended as passive investment products.',
  'No reward is guaranteed.',
  'There is no guaranteed RWA reward, no guaranteed staking reward, no guaranteed creator-fee distribution, no guaranteed platform-fee distribution, no guaranteed treasury reward, no guaranteed agent-profit distribution, no guaranteed capital-management profit distribution, no guaranteed attention-market distribution, no guaranteed computation-market distribution, no guaranteed research reward, no guaranteed synthetic data reward, no guaranteed airdrop, no guaranteed future token, no guaranteed buyback, no guaranteed burn, no guaranteed floor, no guaranteed APY, no guaranteed yield, no guaranteed price support, no guaranteed liquidity and no guaranteed listing.',
  'Any reward program may be modified, delayed, restricted, cancelled or denied.',
  'Eligibility may depend on participation, jurisdiction, KYC, tax, platform rules, issuer rules, technical constraints, treasury availability, legal review, anti-Sybil checks, medical-safety review, scientific-integrity review, research-integrity review or other conditions.',
  '41. User Responsibility, Risks and Project Changes',
  'Each user is responsible for verifying official mint addresses, official contract addresses, official chain selection, official links, official vote addresses, official treasury addresses, official accounts and official disclosures.',
  'Each user is responsible for their own wallet security, tax analysis, legal compliance, jurisdictional eligibility, trading decisions, staking decisions, voting decisions, prediction-market decisions, medical interpretation, scientific interpretation, research interpretation and risk management.',
  'The project is not responsible for user losses caused by market movement, user error, wallet compromise, phishing, wrong-address transfers, wrong-chain transfers, platform changes, smart contract bugs, third-party failures, medical misunderstanding, scientific misunderstanding, research misunderstanding or reliance on AI-generated output.',
  'Participation is highly risky.',
  'Risks include total loss, token price collapse, illiquidity, volatility, bot activity, sniper activity, whale dumping, market manipulation, smart contract failure, wallet compromise, launchpad failure, Solana network issues, Base chain network issues, EVM approval risk, fake contract risk, fake token risk, bridge failure, oracle failure, prediction-market losses, perpetuals liquidation, derivative losses, agent losses, autonomous execution errors, computation-market failures, attention-market failures, capital-management failures, talent-market failures, RWA restrictions, KYC failure, tax liability, regulatory changes, product failure, game failure, website failure, model failure, agent-harness failure, open-source license issues, IP disputes, patent disputes, research errors, synthetic data errors, medical misinformation, scientific misinformation, infrastructure costs, operator error, security exploits, phishing, fake token clones, fake websites, fake vote addresses, fake airdrops, fake support accounts and community collapse.',
  'The project may change.',
  'Utilities, token mechanics, launch venues, chains, agent authority, treasury policy, voting rules, reputation rules, daily task mechanics, season scoring, game features, media features, ad systems, prediction integrations, RWA reward programs, patent strategy, world-launch systems, open-source strategy, software licensing, computation markets, attention markets, creator marketplaces, capital-management systems, talent-management systems, research systems, synthetic data systems, CancerHawk features, HyperKaon features, Asimog features, Tianezha features and disclosures may be modified, delayed, restricted, abandoned or replaced.',
  'No roadmap item is guaranteed.',
  '42. Answer to the Ultimate Question of Life, the Universe and Everything',
  '$pMYTH and $bMYTH are experimental HyperMyths faction tokens.',
  '$pMYTH is intended to launch through Pump on Solana.',
  '$bMYTH is intended to launch through Clanker on Base chain.',
  'There is currently no corporation or formal legal entity behind the project unless separately announced.',
  'There is only a single pseudonymous human operator and near-autonomous agents experimenting with gamified internet capital markets, AI media, MMO alternate reality gameplay, agent systems, prediction markets, computation markets, token worlds, synthetic data generation quests, research simulations and community coordination.',
  'HyperMyths is an experiment in gamified internet capital markets and Frontier AI Research tokenization.',
  'Token communities may become playable factions that test models, test agents, test open-source software, generate media, buy ads, run predictions, price computation, launch worlds, complete daily tasks, vote by token transfer, earn reputation, run cancer synthetic data generation quests, run physics synthetic data generation quests and fight weekly seasons.',
  'The intended world ecosystem includes HyperMyths as the AI media and myth engine, Polymyths as the game-world, server, governance and faction coordination layer, HyperTian as the advertising and attention layer, CancerHawk as the cancer synthetic data generation quest layer, HyperKaon as the physics synthetic data generation quest layer, Asimog as the autonomous-agent log and Tianezha as the computation-market layer.',
  'Asimog and Tianezha are not currently functional and should not be relied on as available products.',
  'All related software should be treated as experimental beta software.',
  'Some parts may be made open source at the project’s discretion, but no holder has a right to force open-sourcing or claim ownership of private code, patent materials, agents, models, systems, computation markets, attention systems, talent systems, capital-management systems, research systems, synthetic data systems or research outputs.',
  'There are no guaranteed managerial efforts. There are no guaranteed marketing efforts. There is no guarantee that anyone will keep building, marketing, promoting, managing, supporting, listing, maintaining liquidity for, researching, computing or increasing the value of $pMYTH or $bMYTH.',
  'The project, operator, agents or future related persons or entities may apply for investments, grants, accelerator programs, hackathons, prizes, sponsorships, loans, venture funding, strategic partnerships, commercial contracts, research opportunities, computation opportunities or other opportunities.',
  'Those off-chain matters are not governed by token holders.',
  'Token-holder governance, if any, applies only to the game world, faction mechanics, community proposals, product signaling, reputation systems, voting rituals and ecosystem gameplay through Polymyths.',
  'Timelines may vary. Daily tasks may change. Weekly seasons may change. Roadmaps may change. Research quests may change. Synthetic data generation quests may change. Computation markets may change. No timeline, task, season, reward, launch, research output, synthetic dataset, computation output or milestone is promised.',
  'The autonomous or near-autonomous agents may learn and operate broadly across markets, chains, prediction systems, research simulations, software systems, synthetic data generation workflows and game systems, but agents are not guaranteed profit machines and are not managing money for token holders.',
  'CancerHawk may support cancer research simulations and cancer synthetic data generation quests, but it is not medical advice, not clinical proof, not diagnosis, not treatment and not a healthcare service.',
  'HyperKaon may support physics research simulations and physics synthetic data generation quests, but it is not scientific proof, not peer review, not lab validation, not engineering certification and not a scientific institution.',
  'The project may involve patents and intellectual property, but tokens do not grant ownership of those patents or IP.',
  'The project is not affiliated with any third party unless expressly announced by both sides.',
  'There is no guaranteed profit. There is no guaranteed floor. There is no guaranteed APY. There is no guaranteed yield. There is no guaranteed RWA. There is no guaranteed future token. There is no guaranteed agent profit. There is no guaranteed attention-market profit. There is no guaranteed capital-management profit. There is no guaranteed computation-market reward. There is no guaranteed research reward. There is no guaranteed synthetic data reward. There is no guaranteed medical result. There is no guaranteed scientific result. There is no guaranteed reward. There is no guaranteed survival.',
  'Participate only if you understand the risks and want to participate in the experiment.',
];
